### ISSUE TITLE
Ionic support?

### ISSUE THREAD

**Issue by MTRNord** [dpa99c/cordova-diagnostic-plugin#100]
When using following with Ionic it gaves me: `Uncaught TypeError: Cannot read property 'diagnostic' of undefined`

Code:
```
cordova.plugins.diagnostic.requestLocationAuthorization(function(status){
    switch(status){
        case cordova.plugins.diagnostic.permissionStatus.NOT_REQUESTED:
            console.log("Permission not requested");
            break;
        case cordova.plugins.diagnostic.permissionStatus.GRANTED:
            console.log("Permission granted");
            break;
        case cordova.plugins.diagnostic.permissionStatus.DENIED:
            console.log("Permission denied");
            break;
        case cordova.plugins.diagnostic.permissionStatus.DENIED_ALWAYS:
            console.log("Permission permanently denied");
            break;
    }
  }, function(error){
    console.error(error);
  });
```

**Comment by dpa99c** [comment]
This plugin will work fine when running in an Ionic app in a [native mobile environment](https://github.com/dpa99c/cordova-diagnostic-plugin#native-environment-required). 

If you are trying to use a browser-emulated environment (i.e. `ionic serve`) , this plugin will not work because it is intended to run in a native mobile environment on a real device.

If you are testing on a real device and encountering this issue, please specify which platform (e.g. Android) , platform version (e.g. cordova-android@5.0.0), plugin version (e.g v3.1.1) you are  using.

**Comment by MTRNord** [comment]
Hi,
I use an One Plus One with Cyanogenmod 13 which is basicly Android 6.0.1.
It is fully rooted and the Log comes when I use adb to use the Code Inspector

**Comment by dpa99c** [comment]
This error is indicative of the plugin not being loaded at the point of invocation.

Ensure you are making the call once the `deviceready` event has fired: Cordova plugins are loaded dynamically so are not guaranteed to be defined until `deviceready`. 

Try building and running the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) to validate that your build environment is working correctly with the plugin and as a reference for its usage.

You can also connect a remote debugger via Chrome dev tools and place a breakpoint on the call to the plugin. At this point, you can check if the diagnostic.js source file has been loaded into the page.

**Comment by MTRNord** [comment]
Ah I see i didn't put it in the ready function xD but thx for support
