### ISSUE TITLE
isCameraAuthorized() / requestCameraAuthorization() not checking on camera permission

### ISSUE THREAD

**Issue by jaysonwm** [dpa99c/cordova-diagnostic-plugin#102]
Good day,

I updated this plugin to v2.3.16 on my cordova project, as i have noticed through the changelog,  

>v2.3.16  
Update Android variant of camera authorization methods to request CAMERA permission in addition to READ_EXTERNAL_STORAGE. This is due to permission changes in cordova-plugin-camera@2.2.0.  

and in the documentation at camera permissions,

> This requests / checks permission for both READ_EXTERNAL_STORAGE and CAMERA run-time permissions which must be added to AndroidManifest.xml

After implementing the `requestCameraAuthorization()`, i found out it only requested for storage permission only. Then again, i checked through `isCameraAuthorized()`, with only storage permission allowed, it returned true, which is not expected.  

While i can use `requestRuntimePermissions()` to request both storage and camera permission, by checking these permission using `isCameraAuthorized()` with camera permission being denied, it will still return true.  

I even went to the app setting, manually allow camera permission and denied storage permission. Then checked with `isCameraAuthorized()`, it returned false.

Did i miss out anything important here?

I'm using:
- cordova.plugins.diagnostic 2.3.16
- cordova-plugin-camera 2.2.0
- Samsung S5 android v6.0.1

**Comment by dpa99c** [comment]
Please update your plugin version - the latest is v3.1.1 and contains numerous bug fixes and improvements.

As you can see from the Android source code, both [`requestCameraAuthorization()`](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/www/android/diagnostic.js#L666) and [`isCameraAuthorized()`](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/www/android/diagnostic.js#L699) include the CAMERA permission.

If updating the plugin doesn't resolve the issue, I recommend building and running the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) to validate the plugin, since it makes use of `requestCameraAuthorization()` ([see here](https://github.com/dpa99c/cordova-diagnostic-plugin-example/blob/master/www/js/index.js#L33)) and `isCameraAuthorized()` ([see here](https://github.com/dpa99c/cordova-diagnostic-plugin-example/blob/master/www/js/index.js#L326)).

**Comment by jaysonwm** [comment]
Updating the plugin to the latest version worked for me.  

It might not worked before because I did not remove the plugin using `cordova plugin rm` command, but what I did was deleting the plugin directly from the folder, and therefore while I reinstall the plugin, the code was fetched, but did not reinstall in my android and ios project.

Anyway, thanks for the reply.
