### ISSUE TITLE
Issue with library in ionic project

### ISSUE THREAD

**Issue by sarunkumar1990** [dpa99c/cordova-diagnostic-plugin#103]
Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Landroid/support/
v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoV
ersionImpl;
    UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/v4/acce
ssibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionI
mpl;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:591)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:546)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:528)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:50
4)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)

:transformClassesWithDexForDebug FAILED

FAILURE: Build failed with an exception.

BUILD FAILED

Total time: 25.583 secs
* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.pro
cess.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.
common.process.ProcessException: org.gradle.process.internal.ExecException: Proc
ess 'command 'C:\Program Files\Java\jdk1.8.0_60\bin\java.exe'' finished with non
-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.
Error: cmd: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\poorvika\platforms\android\src\cordova\plugins\Diagnostic.java uses unc
hecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Landroid/support/
v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoV
ersionImpl;
    UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/v4/acce
ssibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionI
mpl;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:591)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:546)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:528)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:50
4)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.pro
cess.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.
common.process.ProcessException: org.gradle.process.internal.ExecException: Proc
ess 'command 'C:\Program Files\Java\jdk1.8.0_60\bin\java.exe'' finished with non
-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

**Comment by dpa99c** [comment]
This error is almost certainly caused because one or more other plugins in your project is requiring a different version of the Android Support Library. 

This plugin [requires `v4:23.+`](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/plugin.xml#L56), so it's likely another plugin (or plugins) is either requesting a different version through Gradle or is directly including the library as a JAR file. 

Strictly speaking, this isn't as such a bug with this plugin, but an incompatibility issue when using it with other plugins.

To resolve this, you firstly need to figure out which other plugins are requesting the library and what versions. The easiest way to do this, is go through each of the plugin folders in your project's `plugins/` folder and look at the `plugin.xml` for each plugin. Look for any that contain lines like `<framework src="com.android.support:support-v4:+" />` because these are Gradle dependency references to the library. Also look for any lines like `<source-file src="src/android/com/plugin/android-support-v4.jar" target-dir="libs/"/>` where the library is directly included as a JAR.

It depends on what the nature of the conflict is as to how to resolve it, so if you post your findings here, i.e. which plugin(s) is conflicting with this one, I'll try to help you resolve the issue.

**Comment by sarunkumar1990** [comment]
i added the jar file in my plugin. now i got new error. ng-cordova is not working.

**Comment by dpa99c** [comment]
> ng-cordova is not working 

This is not enough information to determine if a bug exists within this plugin, but it's highly unlikely that error is caused by this plugin.

Please supply specific details including:

- Full verbose of the error
- Details of your build environment: Cordova version, cordova-android platform version, plugin version, other plugins
- An isolated code snippet which invokes the plugin and can be used to reproduce the error
-  OR, if possible, post an archive file containing an example Cordova project which illustrates the issue.

Without this information, it's not possible to determine whether this plugin has anything to do with the error and the issue will be closed.

**Comment by sarunkumar1990** [comment]
Error: ng-cordova.js: Uncaught TypeError: Cannot read property 'register' of undefined

ionic version:1.7.16
cordova android version:5.2.1
cordova version :6.3.0

plugins:
com.phonegap.plugins.PushPlugin
com.vliesaputra.deviceinformation
cordova.plugins.diagnostic
cordova-plugin-compat
cordova-plugin-device
cordova-plugin-device-motion
cordova-plugin-geolocation
cordova-plugin-inappbrowser
cordova-plugin-shake
cordova-plugin-whitelist


when i include cordova.plugins.diagnostic  plugin i got error. when i remove this plugin its working fine.

**Comment by dpa99c** [comment]
The [Android Javascript component of this plugin](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/www/android/diagnostic.js) has no 'register' property, so if this error is occurring only after installing this plugin, it's most likely because it's conflicting with another plugin over the `cordova.plugins` namespace.

My suggestion would be to use [Chrome Dev Tools to connect a remote debugger](http://geeklearning.io/apache-cordova-and-remote-debugging-on-android/) to the Android device while the app is running. This should give you a stack trace and enable you to find the line where this error is occurring and with which plugin.

**Comment by sarunkumar1990** [comment]
![image](https://cloud.githubusercontent.com/assets/7007231/17395480/39a755d6-5a4c-11e6-9a5a-ecf459420423.png)

**Comment by dpa99c** [comment]
The first error "device is not defined" is being raised by line 1907 of controllers.js, however without seeing what this line of code is, I cannot help you diagnose which plugin is conflicting. Please post line 1907 of controllers.js, or even better the whole contents of controllers.js

As for the second error, "Cannot read property 'register' of undefined", without seeing the expanded stack trace and the the lines of code it references, I cannot help you diagnose the issue, so please post the expanded stack trace along with the referenced lines of code (or entire referenced files).

**Comment by sarunkumar1990** [comment]
controller('FeedCtrl', function($scope,$http,$timeout,$cordovaGeolocation,$cordovaDevice,$location,$ionicLoading) {
$scope.feed = {};

 var res;
  var lat;
  var lon ;
  var imei,simoperator,simserialno;
  var device = $cordovaDevice.getDevice();
  var model = $cordovaDevice.getModel();
  
  
  $scope.feed.showroom = 2;
  $http.get('http://app.poorvikamobile.com/index.php?route=feed/rest_api/getshowroomarea')
  .success(function(data) {
  console.log(data);
				$scope.showrommarea = data.area;
	})
  $scope.setshowroom = function(data){
	$http.post('http://app.poorvikamobile.com/index.php?route=feed/rest_api/getshowroomdetails',{"area_id":data})
  .success(function(data) {
  console.log(data);
				$scope.showrommareadetail = data.area;	
	})
  }
  $scope.setshowroom(2);

  
  
 var deviceInfo = cordova.require("cordova/plugin/DeviceInformation");
deviceInfo.get(function(result) {
	

     res=JSON.parse(result);
	 
      //fetch the device data
	
        console.log(res);
    }, function(er) {
		 console.log(er);
        console.log("error");
    
	}); 
	
	$timeout(function(){console.log(res);},500); 
	 if (window.localStorage['geolocation']){
		var geolocation = JSON.parse(window.localStorage['geolocation']);
		lat = geolocation.lat;
		lon = geolocation.lon;
	 } else {
		lat = 0;
		lon = 0;
	 }


$scope.feedbackform = function(feed) { 
console.log(res);
	var name = feed.name;
	var email = feed.email;
	var mobileno=feed.mobileno;
	var showroom=feed.address;
	var address=feed.address;
	var feedback=feed.feedbk;
	var softwareversion=device.version;
	var imei=res.deviceID;
	var simoperator=res.netName;
	var simserialno=res.simNo;
	var subscriber=device.uuid;
	
	var networktype='gsm';
	
	var phonetype=device.platform;
	console.log(subscriber+phonetype+softwareversion);
		$http.post('http://www.poorvikamobile.com/app/index.php?route=feed/rest_api/feedback_form',{ 'name':name,'phone_no':mobileno ,'comment':feedback,'imei':imei,'software_version':softwareversion,'sim_operator':simoperator,'sim_serial_no':simserialno,'model':model,'subscriber_id':subscriber,'lat':lat,'lon':lon,'network_type':networktype,'phone_type':phonetype,'email':email,'showroom':showroom,'address':address,'feedback':feedback}
                    ).success(function(data) {
					console.log(data);
					var success = data.success;
					if(data.success){
						$ionicLoading.show({template: 'Feedback Posted Successfully.',duration:2000});
						$timeout(function(){$location.path("/app/home");},2000);
					}else{
						$ionicLoading.show({template: 'Network error.Please retry / FIll Details Correctly',duration:1000});
					}
						 
						
                    }).error(function(data, status) {
					 return data;
                        $scope.errors.push(status);
                    });
	
}
  
})

**Comment by sarunkumar1990** [comment]
Any Idea about my error?

**Comment by dpa99c** [comment]
The first error "device is not defined" is being raised by this line:

    var device = $cordovaDevice.getDevice();

This error has nothing to do with this plugin.

The second error -"Cannot read property 'register' of undefined" - I cannot diagnose because you haven't posted the full stack trace and there's no reference to a 'register' property in your source code. 

Trying to diagnose if this plugin is conflicting with another within the context of your application is not a sensible way to proceed. These errors could easily be caused by logical errors in your code - without seeing the entire source code that's not possible to determine and I don't have time to debug your entire app.

Please create an isolated test project which clearly illustrates if such a problem exists, zip the project source code and post it here. Otherwise this issue will be closed.
