### ISSUE TITLE
Error TS2339: Prop erty 'isLocationEnabled' does not exist on type 'typeof Diagnostic'

### ISSUE THREAD

**Issue by vuhung3990** [dpa99c/cordova-diagnostic-plugin#109]
hello, this error appear when using ionic native please help

`Diagnostic.isLocationEnabled().then(status => {
            if (status) {
                this.getCurrentLocation();
            } else
                this.whenLocationServiceDisable();
        });`

**Comment by dpa99c** [comment]
This is because you are not using the plugin correctly. For starters, the plugin is exposed via the global `cordova.plugins.diagnostic` not `Diagnostic`.

Please read [the documenation](https://github.com/dpa99c/cordova-diagnostic-plugin#islocationenabled) and see the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) for usage examples.
