### ISSUE TITLE
Support for android 6 App Permissions ?

### ISSUE THREAD

**Issue by QuentinFchx** [dpa99c/cordova-diagnostic-plugin#11]
I don't know what is the state of android 6, but I know they'll use the "same" permissions system than iOS.
Will this library support them ?

**Comment by dpa99c** [comment]
I've currently left manifest permissions out of this plugin, since you may or may not use some or all of its functionality and therefore need the relevant permissions. So rather than have the plugin request all the permissions related to its functionality, it's left up to the app developer to choose which he wants to use via the config.xml

That said, the Android 6 run-time permissions is a different kettle of fish. From what I understand, manifest permissions will still be required, but some "dangerous" permissions will also required explicit run-time requests via a new API. So if I get time, I may extend this plugin to be able to make the run-time requests as outlined here: http://developer.android.com/training/permissions/requesting.html

**Comment by colonelchlorine** [comment]
Also very interested in this topic. +1 from me

**Comment by dpa99c** [comment]
Support for Android 6 runtime permissions added in cordova-plugin-diagnostic@2.3.0

There an [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-android-runtime-example) which illustrates use.
