### ISSUE TITLE
iOS 9.3 on getLocationAuthorizationStatus returns DISABLED even if it is enabled

### ISSUE THREAD

**Issue by elektray** [dpa99c/cordova-diagnostic-plugin#111]
On first time running of the app, the getLocationAuthorizationStatus returns NOT DETERMINED instead of NOT REQUESTED. This bug has been noticed on iOS 9.3.
On subsequent loads the issue is not present.

**Comment by dpa99c** [comment]
I think is down to confusion of the literal value vs. the constant name, which arises from my attempt to "smooth over" the differing naming conventions between Android and iOS native permissions.

The [native iOS layer of the plugin](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/src/ios/Diagnostic.m#L834) maps the native `kCLAuthorizationStatusNotDetermined` constant to the string `"not_determined"`. The JS layer then [maps this to the constant](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/www/ios/diagnostic.js#L31) `cordova.plugins.diagnostic.permissionStatus.NOT_REQUESTED`.

So, yes, the literal value is `"not_determined"`, but if you reference it via the constant, e.g. `if(status === cordova.plugins.diagnostic.permissionStatus.NOT_REQUESTED)`, then this can be used across platforms since the [Android implementation uses the same mapping](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/www/android/diagnostic.js#L85).

**Comment by elektray** [comment]
Thanks for the clarification. It makes sense now.
The only thing I'm not sure about is the mapping at the JS level. When I stored `cordova.plugins.diagnostic.permissionStatus` to a variable to define an `if` behaviour, the variable status returned was `NOT_DETERMINED`. At what stage the JS mapping occurs? Is it possible that on first load is not fired?

**Comment by dpa99c** [comment]
The [mapping](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/www/ios/diagnostic.js#L31) is created when the plugin is dynamically loaded in by Cordova, so will be defined by the time the "deviceready" event is fired.

The value of the constant `cordova.plugins.diagnostic.permissionStatus.NOT_REQUESTED` is `not_determined`, but so long as you use the constant itself for comparison, it should work for both Android and iOS, for example:

    if(status === cordova.plugins.diagnostic.permissionStatus.NOT_REQUESTED){

    }
