### ISSUE TITLE
Error on isLocationAuthorized 

### ISSUE THREAD

**Issue by DiogoBatista** [dpa99c/cordova-diagnostic-plugin#112]
Hello there,

First congrats for the awesome plugin, this is precisely what i need for my project.

But unfortunately im having some issues with one specific part of your code.

cordova.plugins.diagnostic.isLocationAuthorized(function(enabled){
    console.log("Location authorization is " + (enabled ? "enabled" : "disabled"));
}, function(error){
    console.error("The following error occurred: "+error);
});

I can log the "enabled" callback but every time i try to perform some validation on that callback result i always have  undefined. I already saw some previous issues and you say is has to be on a deviceready event to have some value, but im testing on a iOS emulator - iphone 6 with Ionic framework. and it always returns undefined. 

even the console.log(cordova.plugins.diagnostic.isLocationAuthorized()) returns a undefined value. 

Can you please help me? 

Thank you and waiting for your reply.

**Comment by dpa99c** [comment]
Due to the nature of the Cordova Javascript-Native bridge, all interactions are asynchronous. Therefore, a callback function is required in all cases in order to asynchronously invoke it from the native layer with the response. 

Therefore, the asynchronous call method will work:

    cordova.plugins.diagnostic.isLocationAuthorized(function(enabled){
        console.log("Location authorization is " + (enabled ? "enabled" : "disabled"));
    }, function(error){
        console.error("The following error occurred: "+error);
    });

whereas attempting to invoke synchronously will return an undefined result:

    console.log(cordova.plugins.diagnostic.isLocationAuthorized())
