### ISSUE TITLE
App pops to foreground if location mode has changed and I have a handler

### ISSUE THREAD

**Issue by ihadeed** [dpa99c/cordova-diagnostic-plugin#114]
Hey there,

I set a handler to listen for changes in Location. If I put the app in the background and change the location mode, the app will pop to foreground immediately. 

This only happens on Android, especially on devices with high RAM that do not need to kill apps in the background. 

Is this a problem with my implementation of the plugin? or is it a small issue with the plugin?

**Comment by dpa99c** [comment]
I can't reproduce this behaviour when testing the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) on Android 6: if I background the app then change the location mode via the quick statusbar dropdown, the app remains backgrounded but I can see the log messages appear in the console.

Can you try to build and run the example project in the device environments that you're seeing this issue in to eliminate any possible causes in your implementation?

**Comment by ihadeed** [comment]
The issue didn't occur in the example project. All the buttons at the end of the page didn't work too.

I also tested my app on cloud services and I didn't have the same issue. Must be just something with my phone or the installed ROM. 

Thanks for your time

**Comment by dpa99c** [comment]
>All the buttons at the end of the page didn't work too.

My bad, I forgot to bump the plugin version in the example project, meaning the example was referencing plugin methods that didn't yet exist. This was why the buttons didn't work. commit [759f68164a01e0baca2838bb9b87e2cb1609bf67](https://github.com/dpa99c/cordova-diagnostic-plugin-example/commit/759f68164a01e0baca2838bb9b87e2cb1609bf67) should have resolved it. So you may want to test again, as the location listener functionality may not have worked correctly either, since the app will have encountered JS errors on initialisation.
