### ISSUE TITLE
iOS 10 - Missing description for NSContactsUsageDescription 

### ISSUE THREAD

**Issue by cmgustavo** [dpa99c/cordova-diagnostic-plugin#118]
After this PR #117, I 'm still getting the same issue from Apple: 

```This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSContactsUsageDescription key with a string value explaining to the user how the app uses this data.```

**Comment by cmgustavo** [comment]
I had to add it manually using XCode: `Privacy - Contacts Usage Description`.

**Comment by cmgustavo** [comment]
Sorry guys, my mistake.

**Comment by douglasjunior** [comment]
+1 for this.

This permission should not be added automatically?

**Comment by douglasjunior** [comment]
Looking at the source code of the `Info.plist` I found the difference.

```xml
...
	<key>NSContactsUsageDescription</key>
	<string>This app requires contacts access to function properly.</string>
	<key>NSContactsUsageDescription </key>
	<string>This app requires contacts access to function properly.</string>
...
```

The key was automatically generated has a space at the end.

**Comment by douglasjunior** [comment]
Sorry, this has been fixed in commit https://github.com/dpa99c/cordova-diagnostic-plugin/commit/4d0097c1d5bb16647ee372fe2b0ed5323e453930

**Comment by dpa99c** [comment]
@douglasjunior While the plugin sets this default message, it's highly recommended that you override it since this is the message displayed to the user as justification as to why they should allow access to their contacts, so tailoring specifically for your app makes it less likely they'll press "Deny". You can do so by manually tweaking the message in the .plist or using [cordova-custom-config](https://github.com/dpa99c/cordova-custom-config) to apply it from your config.xml.

Though I'd avoid a message like `This app requires contacts access so it can send them to a server in Russia and sell them on to cybercriminals` :-D

**Comment by douglasjunior** [comment]
No problem, my App dont use contacts. :D
