### ISSUE TITLE
Android isGpsLocationEnabled() in documentation but not npm module

### ISSUE THREAD

**Issue by colonelchlorine** [dpa99c/cordova-diagnostic-plugin#12]
Did a `cordova plugin add cordova.plugins.diagnostic` and the resultant www/android/diagnostic.js doesn't have that method even though it's in the README.md. Guess npm hasn't been updated?

I'll do add this github repo in the plugin path and it should work.

**Comment by dpa99c** [comment]
The version on [npm](https://www.npmjs.com/package/cordova.plugins.diagnostic) is 2.2.3 which is the latest version, the same as on the master branch of the github repo ([see here](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/package.json#L2)).

`isGpsLocationEnabled() ` was added to the Android version in 2.2.0, so is [still present](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/www/android/diagnostic.js#L37) in the current version.

Check the version of the plugin being installed by looking at the package.json when using `cordova plugin add cordova.plugins.diagnostic`. If it's an older version, make sure you're using an up-to-date version of cordova as older versions will use the now deprecated Cordova plugin registry to source their plugins instead of npm.

**Comment by indralesmana10** [comment]
Sorry if my english is bad. I want to ask to you, how to use cordova.plugins.diagnostic in ionic? I've tried it but still not successful. Can you give me an example of isLocationEnabledSetting()?

**Comment by dpa99c** [comment]
Can this be closed?

**Comment by indralesmana10** [comment]
isLocationEnabledSetting() wokring on ionic framework. but when i use switchToSettings(), not working. sorry for my bad english.

**Comment by dpa99c** [comment]
@indralesmana10 what version of iOS are you testing this on?

**Comment by indralesmana10** [comment]
IOS 9

**Comment by dpa99c** [comment]
`switchToSettings()` is working fine of iOS 9 - take a look (and try building/running) the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example)
