### ISSUE TITLE
Missing UserNotifications/UserNotifications.h

### ISSUE THREAD

**Issue by raphagodoi** [dpa99c/cordova-diagnostic-plugin#124]
after the last update i'm getting this error:

    cordova.plugins.diagnostic/Diagnostic.m:13:9: 'UserNotifications/UserNotifications.h' file not found

**Comment by dpa99c** [comment]
`cordova.plugins.diagnostic@3.2.0` adds support for the new UserNotifications framework added in iOS 10. To build using v3.2.0, you will need to use XCode 8+ because there's no way to conditionally include a framework using the `<framework>` tag in the plugin.xml.

If building locally, you will need to ensure XCode 8 is installed on the build machine.

Currently, cloud-based build platforms such as Phonegap Build, Ionic Cloud and Intel XDK are still using an XCode 7 build environment, so building with `cordova.plugins.diagnostic@3.2` results in this fatal build error.

Therefore, if you are using one of these cloud-based build platform, you should specify `cordova.plugins.diagnostic@3.1` in config.xml until such time as the cloud platform is updated to use XCode 8+.
