### ISSUE TITLE
Success callback never called

### ISSUE THREAD

**Issue by EslamKotb** [dpa99c/cordova-diagnostic-plugin#139]
I am trying to use requestCameraAuthorization to grant permission to camera on Android, but the success call back function.

**Comment by dpa99c** [comment]
Please see the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) which [illustrates how to use `requestCameraAuthorization()` ](https://github.com/dpa99c/cordova-diagnostic-plugin-example/blob/master/www/js/index.js#L56).

Note that [Android runtime permissions](https://github.com/dpa99c/cordova-diagnostic-plugin#android-runtime-permissions) were only introduced in Android 6.0, so calling this function on Android 5 or below will have no effect as the permission is already granted.

**Comment by EslamKotb** [comment]
I am trying on Android 6+ Nexus device.
I am trying the following call
cordova.plugins.diagnostic.requestCameraAuthorization(function(status){
    console.log("Authorization request for camera use was " + (status == cordova.plugins.diagnostic.permissionStatus.GRANTED ? "granted" : "denied"));
}, function(error){
    console.error(error);
});

But it never entered the success callback function, despite the selection I made (Allow, Deny or Always Deny)

**Comment by EslamKotb** [comment]
Sorry for my rude, Thank you for you fast response. I will also try to download your example project and will try to use it on same device. I will update you with the result

**Comment by dpa99c** [comment]
> Sorry for my rude

No worries, you were not rude - just stating the facts, which I appreciate :-)

>  I will also try to download your example project and will try to use it on same device. I will update you with the result

Yes, please do this: testing with an isolated example is the quickest way to eliminate other factors

**Comment by EslamKotb** [comment]
The example worked with me perfectly. I tried to use the same functions in my App

I have noticed the following:

1) When requesting camera permission in my App (I am using the latest version) I got 2 dialog boxes for camera and gallery. while the APK shared with the example displayed only request for camera.

2) I wasn't adding function "registerPermissionRequestCompleteHandler" after added it I got  
success callback. But I only got the callback if i selected Allow. didn't get success callback if I clicked deny or Allows Deny

3) Also I found different in the 2 apps I didn't figure out its reason. "getLocationAuthorizationStatus" on my App never get status ALWAYS_DENIED it get instead NOT_REQUESTED even I have selected always deny

**Comment by dpa99c** [comment]
> 1) When requesting camera permission in my App (I am using the latest version) I got 2 dialog boxes for camera and gallery. while the APK shared with the example displayed only request for camera.

The pre-built APK may be a bit out of date, so not include the more recent plugin functionality such as requesting gallery permission. I'd recommend building the example app in your in your own build environment with the latest version of the plugin and running it from there.

> 2) I wasn't adding function "registerPermissionRequestCompleteHandler" after added it I got success callback. But I only got the callback if i selected Allow. didn't get success callback if I clicked deny or Allows Deny

I'd recommend connecting both apps up for remote debugging via Chrome Dev tools and place breakpoints in the code to compare the difference.

> 3) Also I found different in the 2 apps I didn't figure out its reason. "getLocationAuthorizationStatus" on my App never get status ALWAYS_DENIED it get instead NOT_REQUESTED even I have selected always deny

It's impossible to distinguish between NOT_REQUESTED and DENIED_ALWAYS using the native Android runtime permissions API. They both return the same constant value.

This plugin attempts to distinguish the difference by using local storage to keep track of which permissions have been requested since the app was first installed. On requesting a permission for the first time, an entry is put into local storage against the permission name. If the user then selects DENY_ALWAYS, the plugin uses the flag in local storage to distinguish this from NOT_REQUESTED.

You should be able to try this: uninstall the app and re-install (for the first time). Before requesting any permissions, use Chrome Dev Tools to remotely inspect the Cordova webview on the device/emulator. 
- Open the Resources tab and select Local Storage > file://. You should initially see no entries related to the plugin.
- Then switch to the Sources tab and browse to find the plugin script `diagnostic.js`. Place breakpoints on the functions `updateFirstRequestedPermissions` and `resolveStatus`
- Now request a runtime permission and step through with the debugger. This should indicate why DENIED_ALWAYS is being returned for the first time. Once a permission has been requested for the first time, you should see a relevant entry for its permission group appear in local storage.

Note that if you are using Crosswalk, local storage is apparently unreliable (see #52).

**Comment by EslamKotb** [comment]
Thanks it really helped
