### ISSUE TITLE
NOT_REQUESTED when request is being made.

### ISSUE THREAD

**Issue by rolinger** [dpa99c/cordova-diagnostic-plugin#143]
what would be causing cordova.plugins.diagnostic.requestContactsAuthorization() to be returning NOT_REQUESTED ?  Even though I am requesting it, I never see the "access photos, media & files" popup asking the user for permission (I think this is what the requestContactsAuthorization pop up should say).

The follow are listed in my AndroidManifest.xml file (do I need both?)
```
    <uses-permission android:name="android.permission.GET_ACCOUNTS" />
    <uses-permission android:name="cordova.plugins.diagnostic.runtimePermission.GET_ACCOUNTS" />
```

**Comment by dpa99c** [comment]
It's impossible to distinguish between NOT_REQUESTED and DENIED_ALWAYS using the native Android runtime permissions API. They both return the same constant value.

This plugin attempts to distinguish the difference by using local storage to keep track of which permissions have been requested since the app was first installed. On requesting a permission for the first time, an entry is put into local storage against the permission name. If the user then selects DENY_ALWAYS, the plugin uses the flag in local storage to distinguish this from NOT_REQUESTED.

If the relevant `<uses-permission>` tag is missing from the Android manifest, then the native API will return the NOT_REQUESTED/DENIED_ALWAYS constant value. Since the plugin is unable to make the native permissions request in order to show the native dialog, the plugin will always return NOT_REQUESTED.

For [requestContactsAuthorization()](https://github.com/dpa99c/cordova-diagnostic-plugin#requestcontactsauthorization), the relevant permission is `READ_CONTACTS` so:

    <uses-permission android:name="android.permission.READ_CONTACTS" />

You can see this demonstrated in the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) which [requests the appropriate permission](https://github.com/dpa99c/cordova-diagnostic-plugin-example/blob/master/config.xml#L53) and [invokes requestContactsAuthorization()](https://github.com/dpa99c/cordova-diagnostic-plugin-example/blob/master/www/js/index.js#L82).

**Comment by rolinger** [comment]
I missed the part in the documentation where it said it requires android.permission.READ_CONTACTS - added that it works now.  Sorry for the flub on that one.
