### ISSUE TITLE
iOS location permission messages section missing

### ISSUE THREAD

**Issue by elektray** [dpa99c/cordova-diagnostic-plugin#146]
In the table of contents you have a link to the "iOS location permission messages", but the section is missing from the documentation.

**Comment by dpa99c** [comment]
The ToC link appears to work fine for me and links to the correct section: [https://github.com/dpa99c/cordova-diagnostic-plugin#ios-location-permission-messages](https://github.com/dpa99c/cordova-diagnostic-plugin#ios-location-permission-messages)

**Comment by dpa99c** [comment]
ToC Link:
`- [iOS location permission messages](#ios-location-permission-messages)`

Section:


### iOS location permission messages

When location permission is requested on iOS 8+, a message is displayed to the user indicating the reason for the request. These messages are stored in the `{project}-Info.plist` file under the keys `NSLocationAlwaysUsageDescription` and `NSLocationWhenInUseUsageDescription`, which are displayed when requesting to use location **always** or **when in use**, respectively.

Upon installing this plugin into your project, it will add the following default messages to your plist:

- NSLocationAlwaysUsageDescription: "This app requires constant access to your location in order to track your position, even when the screen is off."
- NSLocationWhenInUseUsageDescription: "This app will now only track your location when the screen is on and the app is displayed."

To override these defaults, you can either edit the messages directly in the plist file, or to persist the changes between platform updates, use my [cordova-custom-config](https://github.com/dpa99c/cordova-custom-config) plugin to add overrides directly from the config xml:

`config.xml`

    <platform name="ios">
        <plugin name="cordova-custom-config" version="*"/>
        <config-file platform="ios" target="*-Info.plist" parent="NSLocationAlwaysUsageDescription">
            <string>My custom message for always using location.</string>
        </config-file>
        <config-file platform="ios" target="*-Info.plist" parent="NSLocationWhenInUseUsageDescription">
            <string>My custom message for using location when in use.</string>
        </config-file>
    </platform>

**Comment by elektray** [comment]
I forgot to specify, it doesn't here:

https://www.npmjs.com/package/cordova.plugins.diagnostic

Thanks for placing the info here. :)

**Comment by dpa99c** [comment]
Seems npmjs has a maximum length for README so is truncating it: [see here](https://github.com/npm/registry/issues/68)

The last section to be included is https://www.npmjs.com/package/cordova.plugins.diagnostic#requestruntimepermission

The following one is not present: https://www.npmjs.com/package/cordova.plugins.diagnostic#requestruntimepermissions

So this is a limitation of npmjs.com, rather than a bug in this plugin's documentation
