### ISSUE TITLE
iOS 10: `authorized_when_in_use` returned but watchPosition fails with code 2 

### ISSUE THREAD

**Issue by mirko77** [dpa99c/cordova-diagnostic-plugin#147]
Hallo!

I am using the same code successfully on iOS 8 and 9, but on 10 the same code fails. 

When trying to get a location after asking for permissions (with  `getLocationAuthorizationStatus()` and getting `authorized_when_in_use`, a call to `navigator.geolocation.watchPosition` fails and the error is:

```

{"code":2,"message":"The operation couldn’t be completed. (kCLErrorDomain error 0.)"}

```

Any suggestion?

I am using Cordova 6.4 and the latest version of your plugin

**Comment by mirko77** [comment]
cordova-ios is  4.3.0

**Comment by dpa99c** [comment]
The issue here is not caused by this plugin, which is correctly requesting the desired location mode: you can confirm this plugin is behaving correctly by requesting `authorized_when_in_use`, then opening the Settings page for app to see that Location is set to "When In Use".

A likely cause is not having the appropriate .plist keys in place for iOS 10 - [see here](http://stackoverflow.com/questions/40210868/corova-geolocation-plugin-use-geolocation-only-when-using-the-app/40211058#40211058)

**Comment by mirko77** [comment]
thanks @dpa99c . I will have to ask that on SO, as my .plist permissions look fine, no?

![plist](https://cloud.githubusercontent.com/assets/1233305/19852358/c3337e08-9f5a-11e6-98e2-58b810bb9648.jpg)

**Comment by dpa99c** [comment]
Yes, those plist entries should be fine, so maybe the problem lies with the geolocation plugin on iOS 10, or with cordova-ios@4.3.0.

I have a Cordova-based app in the iOS app store which is using cordova-ios@4.0.0 and the geolocation plugin and it works fine on iOS 10, however it's requesting authorisation "always", not "when in use". Does you issue go away if you request location to be used "always"?

**Comment by mirko77** [comment]
I have both always and when_is_use keys in the .plist, as I am using watchPosition(); 

I set the permission correctly on the app as well.

Unfortunately, I do not have any iOS 10 device at the moment, I will try again next week when I get hold of one.

**Comment by dpa99c** [comment]
> I have both always and when_is_use keys in the .plist, as I am using watchPosition();

I was just wondering if you observed a difference in the `watchPosition()` result when you use:

    cordova.plugins.diagnostic.requestLocationAuthorization(
        onSuccess, 
        onError, 
        cordova.plugins.diagnostic.locationAuthorizationMode.WHEN_IN_USE
    );

versus:

    cordova.plugins.diagnostic.requestLocationAuthorization(
        onSuccess, 
        onError, 
        cordova.plugins.diagnostic.locationAuthorizationMode.ALWAYS
    );

> Unfortunately, I do not have any iOS 10 device at the moment, I will try again next week when I get hold of one.

Yes, this is best tested on a device rather than simulator
