### ISSUE TITLE
requestLocationAuthorization error with ALWAYS

### ISSUE THREAD

**Issue by rokanost** [dpa99c/cordova-diagnostic-plugin#149]
Hey,

Hope you all are well.

My issue: requestLocationAuthorization() does not work properly when called with ALWAYS parameter. (using ionic 2-rc2). Note.: Calling it without ALWAYS works as expected.

`Diagnostic.requestLocationAuthorization(
Diagnostic.locationAuthorizationMode.ALWAYS
).then(r => {}, e => {});`

Produces:

`Error: The old format of this exec call has been removed (deprecated since 2.1). Change to: cordova.exec(null, null, 'Service', 'action', [ arg1, arg2 ]);`

Cheers,
Rok

**Comment by dpa99c** [comment]
This is an [Ionic Native](https://github.com/driftyco/ionic-native) bug with the [Typescript wrapper for this plugin](https://github.com/driftyco/ionic-native/blob/master/src/plugins/diagnostic.ts), rather than a bug with this plugin itself:

Calling the plugin as you've described through the ionic-native wrapper:

    Diagnostic.requestLocationAuthorization( Diagnostic.locationAuthorizationMode.ALWAYS ).then(r => {}, e => {});
    
actually invokes the underlying plugin with parameters in the wrong order: the [requestLocationAuthorization()](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/www/ios/diagnostic.js#L177) function expects to be passed the arguments `(successCallback, errorCallback, mode)` but the Ionic Native wrapper is passing `(mode, successCallback, errorCallback)` which is causing Cordova to throw the observed error.

I will open an [Ionic Native issue](https://github.com/driftyco/ionic-native/issues) to cover this.

A quick workaround until that issue is fixed is to invoke the underlying plugin function directly:

    declare var cordova: any;
    cordova.plugins.diagnostic.requestLocationAuthorization(
        r => {}, 
        e => {}, 
        cordova.plugins.diagnostic.locationAuthorizationMode.ALWAYS
    );

**Comment by dpa99c** [comment]
Looks like someone already opened an issue covering this in ionic-native: https://github.com/driftyco/ionic-native/issues/776

**Comment by rokanost** [comment]
Awesome, thanks for the prompt response.

**Comment by rokanost** [comment]
Btw, one more bug for ionic-native, constants does not match with responses.
