### ISSUE TITLE
CordovaActivity destroyed when requesting permissions

### ISSUE THREAD

**Issue by oscarnyl** [dpa99c/cordova-diagnostic-plugin#154]
I'm attempting to use this plugin to request permissions at runtime on Android 6.0+ with the following code:
    cordova.plugins.diagnostic.requestRuntimePermissions(function(statuses) {
        for (var permission in statuses) {
            console.log('[Debug] ' + permission + ' status: ' + statuses[permission]);
        }
    }, error, [cordova.plugins.diagnostic.permission.ACCESS_COARSE_LOCATION,
        cordova.plugins.diagnostic.permission.ACCESS_FINE_LOCATION,
        cordova.plugins.diagnostic.permission.CAMERA]);

    cordova.plugins.diagnostic.registerPermissionRequestCompleteHandler(
        function(statuses) {
            console.log('[Debug] Permission request complete');
            for (var permission in statuses) {
                switch(statuses[permission]) {
                    case cordova.plugins.diagnostic.permission.GRANTED:
                        console.log('[Debug] Permission granted: ' + permission);
                        break;

                    case cordova.plugins.diagnostic.permission.NOT_REQUESTED:
                        console.log('[Debug] Permission not requested: ' + permission);
                        break;

                    case cordova.plugins.diagnostic.permission.DENIED:
                        console.log('[Debug] Permission denied: ' + permission);
                        break;

                    case cordova.plugins.diagnostic.permission.DENIED_ALWAYS:
                        console.log('[Debug] Permission denied always: ' + permission);
                        break;
                }
            }
        });

However, when the permission request dialog pops up the application exits. Relevant part of logcat logs when the issue occurs:

    11-15 09:22:11.098 28171 28171 D CordovaWebViewImpl: onPageFinished(file:///android_asset/www/index.html)
    11-15 09:22:11.118 28171 28239 W PluginManager: THREAD WARNING: exec() call to Diagnostic.requestRuntimePermissions blocked the main thread for 48ms. Plugin should use CordovaInterface.getThreadPool().
    11-15 09:22:11.125 28171 28171 E chromium: [ERROR:layer_tree_host_impl.cc(2233)] Forcing zero-copy tile initialization as worker context is missing
    11-15 09:22:11.127 28171 28171 D CordovaActivity: Paused the activity.
    11-15 09:22:11.132  4736 21171 I WindowManager: Destroying surface Surface(name=package.name.omitted/package.name.omitted.MainActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.removeLocked:1449 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2478 com.android.server.wm.WindowManagerService.removeWindowLocked:2436 com.android.server.wm.WindowManagerService.removeWindowLocked:2305 com.android.server.wm.WindowManagerService.removeWindow:2300 com.android.server.wm.Session.remove:193 
    11-15 09:22:11.374 28171 28208 D NetworkSecurityConfig: No Network Security Config specified, using platform default
    11-15 09:22:11.425  4736  4786 I ActivityManager: Displayed com.google.android.packageinstaller/com.android.packageinstaller.permission.ui.GrantPermissionsActivity: +282ms
    11-15 09:22:11.699 28171 28171 D CordovaActivity: Stopped the activity.
    11-15 09:22:11.702 28171 28171 D CordovaActivity: CordovaActivity.onDestroy()

**Comment by dpa99c** [comment]
This is a consequence of how Android 6+ handles run-time permissions requests.

When you call `cordova.plugins.diagnostic.requestRuntimePermissions()`, the plugin [makes the permissions request](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/src/android/Diagnostic.java#L751) via the [Cordova helper method](https://github.com/apache/cordova-android/blob/master/framework/src/org/apache/cordova/CordovaInterfaceImpl.java#L224).

This causes Android to instantiate a new Activity (GrantPermissionsActivity) and switch it into the foreground, which as a consequence puts your app's CordovaActivity into the background (pausing it).

However, once an Activity is in the background, the Android OS may choose to kill the Activity instance, such as in low-resource scenarios (where the device is low on memory or storage). In this case, Android will kill your activity, but then create new instance of it once the GrantPermissionsActivity has completed. With a Cordova app, this effectively means your app will be restarted.

As the [Android run-time permissions documentation] states:

> This method may start an activity allowing the user to choose which permissions to grant and which to reject. Hence, you should be prepared that your activity may be paused and resumed. Further, granting some permissions may require a restart of you application. In such a case, the system will recreate the activity stack before delivering the result to your onRequestPermissionsResult(int, String[], int[]).

There is nothing this plugin can do to prevent Android from killing your app's activity once it has been backgrounded - this is the intended behaviour of the Android OS.

However, I see your problem, in that your app is not being notified of the outcome, because its activity is being restarted, which means the new CordovaActivity instance has lost its reference to the registered Javascript callbacks.

As a workaround, you can call [getPermissionsAuthorizationStatus()](https://github.com/dpa99c/cordova-diagnostic-plugin#getpermissionsauthorizationstatus) when your app first starts (on `deviceready`) to check the state of run-time permissions. This will allow you to check the outcome of the permissions request, should your app activity be killed off while requesting a permission.

It may be possible to enhance this plugin to better handle this scenario by handling the native callback from `onRequestPermissionsResult(int, String[], int[])` when the app's activity is restarted, but it's not something I have time do to in the near future.

**Comment by oscarnyl** [comment]
>However, once an Activity is in the background, the Android OS may choose to kill the Activity instance, such as in low-resource scenarios (where the device is low on memory or storage). In this case, Android will kill your activity, but then create new instance of it once the GrantPermissionsActivity has completed. With a Cordova app, this effectively means your app will be restarted.

I would be ok with this being the case, this does however not occur. After dealing with the permissions the user is left outside the application.

**Comment by dpa99c** [comment]
This is strange behaviour - can you give the following information where you are observing this:

- Android device model
- Android version on device
- Android target SDK version
- Cordova android platform version

**Comment by oscarnyl** [comment]
* Nexus 6P
* Android 7.0
* I have not specified a target SDK version, hence it should be the minimum sdk version I specified - 16
* cordova-android 6.1.0

**Comment by dpa99c** [comment]
cordova-android@6.1.0 has a default target SDK version of 25 (Android 7.1).

I don't have a device running Android 7, but I'm not able to reproduce your observed issue in the Android 7.0 or 7.1.1 emulators using the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) when built with cordova-android@6.1.0

Could you try building and running the example project both on the Android 7 emulator and on your device to see if the issue happens there.

**Comment by oscarnyl** [comment]
I managed to solve the issue to a "good enough" state by changing the target sdk version to 16, but I'll try to run it through an emulator just to follow up on the problem (and possibly test it on a device running 6.0).

**Comment by oscarnyl** [comment]
I'm getting an unrelated issue when running the application on an emulator (the app crashes on launch, from what I understand because it is using Crosswalk).
