### ISSUE TITLE
requestLocationAuthorization error on iOS7

### ISSUE THREAD

**Issue by s2young** [dpa99c/cordova-diagnostic-plugin#17]
Gettiing the following error after calling 'requestLocationAuthorization' method on iOS 7 device:

[CLLocationManager requestWinInUseAuthorization]:
unrecognized selector sent to instance 0x194812c0

**Comment by dpa99c** [comment]
Runtime location authorization was introduced in iOS 8 ([see here](https://developer.apple.com/library/ios/documentation/CoreLocation/Reference/CLLocationManager_Class/#//apple_ref/occ/instm/CLLocationManager/requestWhenInUseAuthorization)) hence the error on iOS 7.

**Comment by s2young** [comment]
Ah, OK.  I must have missed this in the docs?  How do I go about getting location on iOS7?  Just ask via getCurrentLocation?

**Comment by dpa99c** [comment]
I will add a fix to the plugin for this. In the meantime, you could just use the device plugin to detect an omit the call on iOS 7 and below:

    if(device.platform == "iOS" && parseInt(device.version) > 7){
        cordova.plugins.diagnostic.requestLocationAuthorization();
    }

**Comment by s2young** [comment]
Yes, indeed.  The fix was to simply go straight to the geolocation plugin's getCurrentPosition method.  Thanks for your help.

**Comment by dpa99c** [comment]
Glad you found a workaround. Still, the plugin should not raise an error because of this, so I have added a patch to ensure `requestLocationAuthorization` is not called on iOS 7 or below, in commit f09c05089f81a99503478a6afb3d06b89a9809ac. Since I'm using the latest Xcode 7, I don't have an iOS 7 simulator available and I don't have a device running iOS 7 so I'm unable to test it, so would appreciate if you could test this patch on iOS 7 by installing the plugin directly from this repo:

    cordova plugin add https://github.com/dpa99c/cordova-diagnostic-plugin

It should no longer cause an error if `requestLocationAuthorization` is called on iOS 7, however it will still have no effect since requesting authorization is not needed on iOS 7.
