### ISSUE TITLE
Issue in security check via Veracode

### ISSUE THREAD

**Issue by joshgarwood** [dpa99c/cordova-diagnostic-plugin#180]
Hey folks!

I'm using this plugin in an ionic 2 project and we recently ran a security scan via Veracode.  The scan returned an error denoting there was `Insufficient Entropy` in the `generateRandom()` method in android/Diagnostic.java.  So my questions are:

1. Is anyone familiar with what may need to be done to fix this method?
2. OR, do you know what the generateRequestId() method is doing and if it's related to security in any way?  If not, we can safely explain that this is not a security risk.

Thanks!

**Comment by dpa99c** [comment]
As can be seen if you [look at the source code](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/src/android/Diagnostic.java#L807), [`generateRandomRequestId()`](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/src/android/Diagnostic.java#L795) simply generates a random number in order to [assign it to a Javascript callback context](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/src/android/Diagnostic.java#L790) which is used when [requesting runtime permissions](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/src/android/Diagnostic.java#L578), the reason being that if you make multiple concurrent requests for runtime permissions, the Javascript callback handlers are given a unique (well, random) identifier so you don't get the wrong handler being called with the wrong permission result.

You can draw what security conclusions you wish from this, but mine is that automated security analysis services such as Veracode are about as good at differentiating false positives from real security threats as @realDonaldTrump...

**Comment by joshgarwood** [comment]
Thanks for the quick response @dpa99c ... I totally agree!  And hilarious that Drumpf has a github account!
