### ISSUE TITLE
HELP WANTED - Any idea why the WebIntent or Custom url scheme does not work?

### ISSUE THREAD

**Issue by shamun** [dpa99c/cordova-diagnostic-plugin#188]
I used this plugin sample: `https://github.com/dpa99c/cordova-diagnostic-plugin-android-runtime-example` on Android 6.0.1 which works great. 

Now i was adding some third party plugins on it such as: [WebIntent](https://github.com/Initsogar/cordova-webintent) and [Custom url scheme](https://github.com/EddyVerbruggen/Custom-URL-scheme).

But with your sample app i can use the Custom url scheme to launch the app, but on launch it never executes the "handleOpenURL" function, please see here details: http://stackoverflow.com/q/43087848/285594

Do you know why even the permissions were granted but `handleOpenURL` never get executed? is it because some permission is still missing in your sample?

Many many thanks.

**Comment by dpa99c** [comment]
There are no permissions missing in the android runtime example - it illustrates and allows granting of all possible Android runtime permissions.

This issue should be raised against the Custom URL Scheme plugin, not this one, because you are asking about functionality related to that plugin, not this one.
