### ISSUE TITLE
getLocationAuthorizationStatus response Error

### ISSUE THREAD

**Issue by idrissHammamiTun** [dpa99c/cordova-diagnostic-plugin#191]
I use getLocationAuthorizationStatus method to get my location status, when I ask "never ask location", I never receive status "DENIED_ALWAYS" but I receive "NOT_REQUESTED" as response. 

cordova.plugins.diagnostic.getLocationAuthorizationStatus(function(status){
    switch(status){
        case cordova.plugins.diagnostic.permissionStatus.NOT_REQUESTED:
            console.log("Permission not requested");
            break;
        case cordova.plugins.diagnostic.permissionStatus.GRANTED:
            console.log("Permission granted");
            break;
        case cordova.plugins.diagnostic.permissionStatus.DENIED:
            console.log("Permission denied");
            break;
        case cordova.plugins.diagnostic.permissionStatus.DENIED_ALWAYS:
            console.log("Permission permanently denied");
            break;
    }
}, function(error){
    console.error(error);
});

**Comment by dpa99c** [comment]
Since it's impossible to distinguish between NOT_REQUESTED and DENIED_ALWAYS using the native Android runtime permissions API (they both return the same constant value), this plugin attempts to distinguish the difference by using HTML5 local storage to keep track of which permissions have been requested since the app was first installed. On requesting a permission for the first time, an entry is put into local storage against the permission name. If the user then selects DENY_ALWAYS, the plugin uses the flag in local storage to distinguish this from NOT_REQUESTED.

Some things to watch out for:

- Clearing local storage will result in this data being lost and will result in NOT_REQUESTED being returned even if the user previously chose to always deny permission.

- If the relevant `<uses-permission>` tag is missing from the Android manifest, then the native API will return the NOT_REQUESTED/DENIED_ALWAYS constant value. Since the plugin is unable to make the native permissions request in order to show the native dialog, the plugin will always return NOT_REQUESTED.

I would suggest looking at the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) which illustrates/validates plugin functionality, [including `getLocationAuthorizationStatus()`](https://github.com/dpa99c/cordova-diagnostic-plugin-example/blob/master/www/js/index.js#L378).
Try build and running it to confirm whether or not you get the same result.

**Comment by dpa99c** [comment]
Closing due to no response from OP
