### ISSUE TITLE
2.3.2 version fails to compile Android on Phonegap Build

### ISSUE THREAD

**Issue by bau720123** [dpa99c/cordova-diagnostic-plugin#20]
hi @dpa99c 
I use PGB cli-5.2.0 with your latest plugin 2.3.2
but it will cause Android build fail
2.3.0 is build fine

here is my log
http://pastebin.com/embed_iframe.php?i=AnBHDiGa

**Comment by dpa99c** [comment]
You are building using Android API 22. Since support for Android runtime permissions was added, you must build using Android API 23

**Comment by bau720123** [comment]
hi @dpa99c 
thanks your reply
I will inform the PGB team
because for now the latest API is only 22....

**Comment by bau720123** [comment]
I have already post a link under here
http://community.phonegap.com/nitobi/topics/the-android-sdk-api-should-be-update-from-22-to-23

**Comment by dpa99c** [comment]
I'll rename this issue to make it clear that it's a Phonegap Build issue and leave it open for reference.

In summary:

- Phonegap Build doesn't yet support API 23 which is required by this plugin for Android 6 runtime permissions
- Keep an eye on the [Phonegap Build](http://phonegap.com/blog/phonegap-build/) blog as to when they will release an update supporting it
- In the meantime, Phonegap Build users should use v2.3.0 the plugin, which will compile with API 22.

**Comment by bau720123** [comment]
thanks @dpa99c reply

**Comment by bill-rousseau** [comment]
I've experienced that problem too, and here's the breakthrough I followed:
-  Android API must actually be 23 and not 22
-  I've noticed that for now, plugin implementation is quite different between github repo and directly with ionic plugin add, be careful if a method you need is not present, you must have to install plugin with the github repo url.
- If your app can't build, you might install a complementary package called "Android Support Repository" as indicated here: http://stackoverflow.com/questions/19621941/android-studio-could-not-find-any-version-that-matches-com-android-supportappco#_=_

In my case I hadd to edit AndroidManifest.xml manually, but you might try dpa99c's cordova-custom-config for more information.

**Comment by dpa99c** [comment]
@bill-rousseau Glad you got your problem solved

> Android API must actually be 23 and not 22

I'm going to create a branch which contains all the code except Android 6 runtime permissions and hence remove dependency on API 23. That will fix (this issue) for Phonegap Build users until PGB moves to API 23 (currently on 22).

>I've noticed that for now, plugin implementation is quite different between github repo and directly with ionic plugin add, be careful if a method you need is not present, you must have to install plugin with the github repo url.

This should not be the case. The current version on the master branch of the github repo is [2.3.8](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/package.json#L2) which is the same version as published to [npm](https://www.npmjs.com/package/cordova.plugins.diagnostic). However, if you're using an old version of the Cordova/Ionic CLI, it will use the Cordova Plugin Registry instead of npm as it's plugin source, and hence would result in installing a much older version of the plugin. Check the CLI tools are up-to-date.

>If your app can't build, you might install a complementary package called "Android Support Repository"

I will update the documentation to explictly state the need for "Android Support Repository" - currently in only specifies that ["Android Support Library"](https://github.com/dpa99c/cordova-diagnostic-plugin#android-runtime-permissions-build-requirements) must be installed.

**Comment by veernimbus** [comment]
I too have the same issue. Unable to set the target android version to 23. I am developing an ionic app using Visual studio 15.

**Comment by dpa99c** [comment]
There's now a branch of the plugin specifically for building against legacy API versions (22 and below): [https://github.com/dpa99c/cordova-diagnostic-plugin/tree/api-22](https://github.com/dpa99c/cordova-diagnostic-plugin/tree/api-22)

Using this branch will resolve the Phonegap Build issue

**Comment by bau720123** [comment]
hi @dpa99c 
but for now
PGB only can use npm resource...
```
<gap:plugin name="pluginname" source="npm" version="XXX" />
```

**Comment by dpa99c** [comment]
@bau720123 doh,  didn't realise that. Going to have to publish this branch to npm under a different plugin id then. Leaving it with me...

**Comment by bau720123** [comment]
OKOK
thanks @dpa99c 
you are awesome

**Comment by dpa99c** [comment]
Legacy version of the plugin is now published to npm under a different plugin ID -  `cordova.plugins.diagnostic.api-22` - so for PGB you should be able to use:

    <gap:plugin name="cordova.plugins.diagnostic.api-22" source="npm" version="2.3.10-api-22" />
