### ISSUE TITLE
Build fail (Could not find :tslocationmanager:)

### ISSUE THREAD

**Issue by crawft** [dpa99c/cordova-diagnostic-plugin#201]
I can't install the plugin, the build is failing. I've checked I have high enough versions of the dependencies mentioned, the error is:

```
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugApkCopy'.
   > Could not find :tslocationmanager:.
     Required by:
         :android:unspecified
```

Any ideas?

**Comment by dpa99c** [comment]
`tslocationmanager` is nothing to do with with plugin. You can confirm this plugin works correctly in isolation by build and running the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example).

Most likely this error is due to another plugin in your project, [cordova-background-geolocation](https://github.com/transistorsoft/cordova-background-geolocation-lt) looks a likely candidate since it references [such a file](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/src/android/libs)
