### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LuizGustavoApp** [dpa99c/cordova-diagnostic-plugin#218]
Hi,
i receive the following error compiling the project with Android Support Library version 41:
Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

Tnx

**Comment by dpa99c** [comment]
The most likely cause is a Gradle version collision caused by another plugin requesting a different version of the Android Support Library (see #211, #205, etc.).
The easiest fix is to install [cordova-android-support-gradle-release](https://github.com/dpa99c/cordova-android-support-gradle-release) into your project to align the versions.
