### ISSUE TITLE
Android manifest Error

### ISSUE THREAD

**Issue by videmort** [dpa99c/cordova-diagnostic-plugin#219]
When I add this plugin I get this error.
Is a conflict with cordova crosswalk plugin
Attribute meta-data#android.support.VERSION@value value=(26.0.0-alpha1) from [com.android.support:support-v4:26.0.0-alpha1] AndroidManifest.xml:27:9-38
	is also present at [com.android.support:appcompat-v7:25.3.1] AndroidManifest.xml:27:9-31 value=(25.3.1).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:41 to override.

**Comment by dpa99c** [comment]
The caused is a Gradle version collision caused by Crosswalk requesting a different version of the Android Support Library (see #212, #211, #205, etc.).
The easy fix is to install [cordova-android-support-gradle-release](https://github.com/dpa99c/cordova-android-support-gradle-release) into your project to align the versions.
