### ISSUE TITLE
iOS granting push notifications  ???

### ISSUE THREAD

**Issue by rolinger** [dpa99c/cordova-diagnostic-plugin#224]
In iOS user's must grant permission, the diagnostic function `isRemoteNotificationsEnabled()` only seems to check if the the permission is granted or not.  Upon app install/initialization (for iOS) I need to get user permissions for push notifications, how can I do this?   I don't see a method for requesting authorization/permission - only to check to see if it is or is not.

**Comment by dpa99c** [comment]
This is something I have previously considered and decided not to implement because it is not straightforward:

On iOS, there is no mechanism to explicitly request permission for remote notifications. Instead it is done implicitly when registering for remote notifications. This is done by calling the native `registerUserNotificationSettings` and `registerForRemoteNotifications` API functions. This can only be done once, and the call to `registerUserNotificationSettings` must contain the notification settings that will be requested. You can see this [being done in phonegap-plugin-push](https://github.com/phonegap/phonegap-plugin-push/blob/master/src/ios/PushPlugin.m#L281).

So in order for this plugin to enable requesting permission for remote notifications, it would have to implement a mechanism to define the notification settings to request, similar to the push notifications plugin. This would be duplicating functionality of the push notifications plugin, which is needed anyway (or an equivalent plugin) to use push notifications unless this plugin was to provide a full implementation of remote notifications, which I consider that to be out of the scope of this plugin.

Hope this makes sense, and let me know if you think I've missed something and there's an easy way this can be achieved.

**Comment by rolinger** [comment]
I follow your logic.  I am using cordova-plugin-firebase (I tried using phonegap-plugin-push...too many problems getting it installed).  Cordova-plugin-firebase provides a `window.FirebasePlugin.grantPermission()` but it doesn't have a callback built into it.  So when my app inits for the first time and iOS Push Permissions are being requested, the popup "grant/deny" does show up, but the rest of my app continues to initialize - i was hoping a proper requestPermissions would provide a proper callback that would allow the app init to pause until the user responded.  I tried wrapping the `grantPermission` in my own but can't get it work.  Code below:

I know this is off topic here for this plugin, but any assistance would help.  I use your `diagnostic` plugin for so much because it does things properly, I use it in lieu of other plugins that are designed to use specific components but don't do the permissions part well at all.  Had hoped there was some `requestPushPermissions` hidden somewhere.  :-)

```
  function iosPush() {
    var q = $q.defer() ;
    if (/(iPad|iPhone|iPod)/i.test(navigator.userAgent)) {
      window.FirebasePlugin.grantPermission(function(status) {
        q.resolve(status) ;
      },function(err) {errMgmt("ctrl/init",35,"iOS Push ask Permission error: "+err) }) ;
    } else {
      q.resolve("Android") ;
    }
    return q.promise ;
  }
    iosPush().then(function(status) {
      return getLocationAuth()
    }).then(function(status) { 
        .....
       .....
    }) ;

```

**Comment by dpa99c** [comment]
Looking at the code for cordova-plugin-firebase, the permission request is [invoked implicitly](https://github.com/arnesson/cordova-plugin-firebase/blob/master/src/ios/FirebasePlugin.m#L79) as outlined above, however it does seem to [provide a callback](https://github.com/arnesson/cordova-plugin-firebase/blob/master/src/ios/FirebasePlugin.m#L88) you can hook into.

However, closing this for reasons outlined above.
