### ISSUE TITLE
Calling isContactsAuthorized() on Android 5 / API 22 and below will always return TRUE

### ISSUE THREAD

**Issue by Benjamin021** [dpa99c/cordova-diagnostic-plugin#235]
If the READ_CONTACTS permission is forbidden by the user, isContactsAuthorized() still returns TRUE. How to deal with this situation?Thanks!

**Comment by dpa99c** [comment]
[As documented](https://github.com/dpa99c/cordova-diagnostic-plugin#iscontactsauthorized):

> Calling on Android 5 / API 22 and below will always return TRUE as permissions are already granted at installation time.

Run-time permissions were only introduced in Android 6.0 / API 23, so requesting permissions on Android 5 or below will always result in true, since they are granted when the app is installed.

See [Android documentation](https://developer.android.com/training/permissions/requesting.html) for more detail.

**Comment by Benjamin021** [comment]
Thank you very much! I mean that the permission is forbidden by the user manually after the app is installed, isContactsAuthorized() still return true. How to get the permission status right?

**Comment by dpa99c** [comment]
The title of your issue says `on Android 5 / API 22`, but on a device running Android 5 (or below) it's not possible for the user to manually forbid permission after an app is installed, as there's no concept of run-time permissions: all permissions are granted at install time and cannot be modified afterwards.

So are you talking about this happening on a device running Android 6 (or above)?

**Comment by Benjamin021** [comment]
No, it's Android 5.1. The user can forbid the permission through the system permission settings of the Phone. After that launching the app,isContactsAuthorized() still return true.

**Comment by dpa99c** [comment]
I'm not sure it's possible to disable permissions on Android 5.1 directly from Settings without rooting the device or using a 3rd party app: here's a screenshot of the permissions area of the App Info page in Settings on Android 5.1 - it's read-only and cannot be changed:

<image src="https://user-images.githubusercontent.com/2345062/30853748-94c6b368-a2a7-11e7-838f-ce659de8c175.png" width="400"/>

But even if a permission can be revoked after installing the app, there's nothing this plugin can do to detect it since Android 5.1 SDK has no concept of run-time permissions, so there's no way to detect it has been revoked since granting permission at install time. 

In this case, the user has actively chosen to deny permission to the app and there's no way to detect this.

**Comment by Benjamin021** [comment]
I get it.
Thank you so much!
