### ISSUE TITLE
[FEATURE] Add support for getExternalSdCardDetails() with Android running on a Chrome OS device

### ISSUE THREAD

**Issue by bigt11** [dpa99c/cordova-diagnostic-plugin#244]
I cant get getExternalSdCardDetails() to work while using an android app on chrome os.  I am using api 25 and android 7.1 on the chrome os device. I am on the dev build 63.0.3236.0 and the device is a C100P.  I know about requesting runtime permissions for "storage"  I have done that, and getExternalStorageAuthorizationStatus() returns that it is authorized.  

getExternalSdCardDetails() returns nothing - blank on the diagnostic test app, and in my code.

chrome-os does have the ability to access the SD card, but I have yet to be able to do it.  Here is the thread for it.  [https://bugs.chromium.org/p/chromium/issues/detail?id=660189](url)

**Comment by dpa99c** [comment]
Running an Android app on Chrome OS isn't the same as running on vanilla Android: the difference in filesystem layout is probably why `getExternalSdCardDetails()` is unable to locate the SD card. 

This plugin makes no claims to support Android apps running on Chrome OS and as such this would be considered an enhancement of existing functionality rather than a bug.

I don't have a device running Chrome OS to develop/test this, but will gladly accept a PR which implements the conditional functionality necessary to locate and return the external SD details for an Android app running on Chrome OS.

**Comment by dpa99c** [comment]
Closed as out-of-scope of supported OS versions
