### ISSUE TITLE
EPERM: operation not permitted,

### ISSUE THREAD

**Issue by RameshkrishnanV** [dpa99c/cordova-diagnostic-plugin#250]
Hi, 
White doing ionic state reset i'm getting this error, only for diagnostic plugin.
ionic version - 1.7
cordova - 6.5

Error: EPERM: operation not permitted, utime '/Users/SmartenSpaces-Dev-RK/.cordova/lib/npm_cache/cordova.plugins.diagnostic/3.7.1/package/package.json'

**Comment by dpa99c** [comment]
This error is due to file permissions during the npm install process and therefore has nothing to do with this plugin directly, which has no control how it has been installed.
[See here](https://blogs.msdn.microsoft.com/matt-harrington/2012/02/23/how-to-fix-node-js-npm-permission-problems/) for a potential solution
