### ISSUE TITLE
huge latency

### ISSUE THREAD

**Issue by canado** [dpa99c/cordova-diagnostic-plugin#254]
Hi,

I compiled my app few weeks ago and the GPS detection was working just fine.
I compiled yesterday and now it takes 2 to 3 min for the GPS to embark.

Can you look into the problem ?

Thanks

**Comment by dpa99c** [comment]
This is by no means enough information to determine if there is an issue.

What platform (iOS/Android/Windows), platform version, plugin version, specific plugin functions are you testing?

What do you mean by "GPS detection" and "GPS to embark"? 
Exactly which plugin functions does this relate to and what is the exact problem?

**Comment by canado** [comment]
Ok so 

Android,samsung s7 ( haven't tested on iOS yet )
cli-7.0.1 (4.4.0 / 6.2.3 / 5.0.0)

cordova.plugins.locationAccuracy.canRequest returns 0 instead of 1
my phone gps is activated


ifI try to do cordova.plugins.locationAccuracy.request even if canRequest = 0
I have code 2 message:application does not have sufficient geolocation permissions
But I guess this would be the normal message in that case

**Comment by canado** [comment]
Also in my config.xml I have
    <gap:plugin name="cordova-plugin-geolocation" source="npm"/>

but the thing is that everything was working just fine before and now it is not.
Were there big changes in the plugin code recently ?

**Comment by dpa99c** [comment]
The functions in the `cordova.plugins.locationAccuracy` namespace are part of [cordova-plugin-request-location-accuracy](https://github.com/dpa99c/cordova-plugin-request-location-accuracy), not this plugin (`cordova-diagnostic-plugin`).

> Were there big changes in the plugin code recently ?

As you can see from [the commit history](https://github.com/dpa99c/cordova-plugin-request-location-accuracy/commits/master) for `cordova-plugin-request-location-accuracy`, there were no changes since 29th August.

> cordova.plugins.locationAccuracy.canRequest returns 0 instead of 1 my phone gps is activated

As the documentation states for [canRequest()](https://github.com/dpa99c/cordova-plugin-request-location-accuracy#canrequest): "On Android, this will return true if the app has authorization to use location."

I.e. this bears no relation to whether your phone gps is activated

> ifI try to do cordova.plugins.locationAccuracy.request even if canRequest = 0
I have code 2 message:application does not have sufficient geolocation permissions

This is to be expected if you call `request()` when the application does not have location permission.
Before you can call `request()`, you application must have run-time permission to use location on Android 6+. One way you can achieve this is by calling this plugin's [requestLocationAuthorization()](https://github.com/dpa99c/cordova-diagnostic-plugin#requestlocationauthorization) function.

Note you need to also ensure appropriate permissions are added to the AndroidManifest.xml - [see here](https://github.com/dpa99c/cordova-diagnostic-plugin#android-permissions)

**Comment by canado** [comment]
Thank you for your reply.
Since I haven't changed my code and  this plugin neither.  What do you think could be the problem ?
I am using phonegap build to compile

**Comment by dpa99c** [comment]
>  What do you think could be the problem ?

Probably Phonegap Build. When using remote build solutions such as this, you have no idea what they've changed in the build environment.

If you're using `<config-file>` blocks in your config.xml to insert `<uses-permission>` elements, note these are no longer supported as of Phonegap Build cli-7.0.1 [see here](http://docs.phonegap.com/phonegap-build/configuring/config-file-element/). That would explain the sudden loss of permission to access location.

**Comment by canado** [comment]
I tested on a friend's iPhone and it is working just fine. So it must be an android compiling problem

**Comment by dpa99c** [comment]
The location accuracy plugin works completely differently on iOS and would not rely on `<config-file>` blocks in `config.xml` to insert `<uses-permission>` for location permission.

**Comment by canado** [comment]
I am not using <config-file> in my config.xml

But I am using this
    <gap:plugin name="cordova-plugin-geolocation" source="npm"/>
    <gap:plugin name="cordova-plugin-request-location-accuracy" source="npm"/>

 <feature name="Geolocation">
        <param name="ios-package" value="CDVLocation" />
    </feature>

**Comment by dpa99c** [comment]
`cordova-plugin-geolocation` should [insert the `<uses-permission>`](https://github.com/apache/cordova-plugin-geolocation/blob/master/plugin.xml#L41) entries then. 

I'd highly recommend moving to a local build environment instead of Phonegap Build as it puts you in complete control of your build environment.
Since you're using Phonegap Build, it's not possible to do any debugging during the build process, so you will need to debug on the device. 

You can debug the Cordova app running inside the Webview using Chrome Dev Tools and the native plugin using Android Studio.

**Comment by canado** [comment]
I completely understand, and it starts to get on my nerves to be honest.

**Comment by canado** [comment]
Sorry to bother you again

I did some digging, and I am still stuck on android.I have done a blank app with just the geolocation

Can you confirm that what I do is correct ?

    first I do

        cordova.plugins.locationAccuracy.canRequest(function(canRequest) {

            //canRequest is always 0 even if the phone location is on or not. I don't know if this is normal.

            if (canRequest) {

            } else {

                cordova.plugins.locationAccuracy.request(function(success) {


                    /*Here it successfully come this far*/

                    var geoOptions = {
                        enableHighAccuracy: true
                    };
                    navigator.geolocation.getCurrentPosition(geolocationSuccess, geolocationError, geoOptions);

                    //then it goes inside geolocationError function.
                    // and in there it says that the permissions are not set. But even when I do cordova.plugins.diagnostic.switchToLocationSettings(); I can see that the location permission is on, which is wierd.

                }, function(error) {
                    alert("error");
                    alert(JSON.stringify(error, null, 4));

                }, cordova.plugins.locationAccuracy.REQUEST_PRIORITY_HIGH_ACCURACY);


            }

        });

**Comment by canado** [comment]
Also I have cloned your project https://github.com/dpa99c/cordova-plugin-request-location-accuracy-example.git

and installed it, and it is not working. even when I switch on/off location.
I am tapping on all 3  buttons

request location
request location authorization
open app settings

and it does nothing.

**Comment by dpa99c** [comment]
> Also I have cloned your project and installed it, and it is not working. even when I switch on/off location.

Presumably you tried building it with Phonegap Build which will not work because the example project [uses a `<config-file`> block](https://github.com/dpa99c/cordova-plugin-request-location-accuracy-example/blob/master/config.xml#L15) to add the necessary `<uses-permission>` entries, which (as mentioned above) are no longer supported by Phonegap Build.

Phonegap Build (like other "cloud" build services) is a 2nd class build enviroment compared with building locally, where you have full control of the source code and build environment.
It lacks core features of Cordova/Phonegap available when building locally: for example, [hook scripts](https://cordova.apache.org/docs/en/latest/guide/appdev/hooks/) which [do not work in Phonegap Build](https://github.com/phonegap/build/issues/425). 
If you're doing anything more than a basic/trivial app, you should build locally.


> Can you confirm that what I do is correct ?

No, it's not. By calling `cordova.plugins.locationAccuracy.canRequest()` before you call the Geolocation plugin, (`navigator.geolocation.getCurrentPosition()`) you have no run-time authorisation to use location, hence `canRequest()` returns 0. 

As I said above, you need to manually request run-time authorisation via the diagnostic plugin, something like this:

	function proceed() {
	    cordova.plugins.locationAccuracy.canRequest(function(canRequest) {
	        if (canRequest) {} else {
	            cordova.plugins.locationAccuracy.request(function(success) {

	                var geoOptions = {
	                    enableHighAccuracy: true
	                };
	                navigator.geolocation.getCurrentPosition(geolocationSuccess, geolocationError, geoOptions);

	            }, function(error) {
	                alert("error");
	                alert(JSON.stringify(error, null, 4));

	            }, cordova.plugins.locationAccuracy.REQUEST_PRIORITY_HIGH_ACCURACY);
	        }
	    });
	}

	function onError(error) {
	    console.error("The following error occurred: " + error);
	}

	function handlePermissionResult(status) {
	    switch (status) {
	        case cordova.plugins.diagnostic.permissionStatus.GRANTED:
	            console.log("Permission granted");
	            proceed();
	            break;
	        case cordova.plugins.diagnostic.permissionStatus.NOT_REQUESTED:
	            console.log("Permission not requested");
	            requestPermission();
	            break;
	        case cordova.plugins.diagnostic.permissionStatus.DENIED:
	            console.log("Permission denied");
	            requestPermission();
	            break;
	        case cordova.plugins.diagnostic.permissionStatus.DENIED_ALWAYS:
	            console.log("Permission permanently denied");
	            // Notify user and switch to settings to manually enable
	            break;
	    }
	}

	function checkPermission() {
	    cordova.plugins.diagnostic.getLocationAuthorizationStatus(handlePermissionResult, onError);
	}

	function requestPermission() {
	    cordova.plugins.diagnostic.requestLocationAuthorization(handlePermissionResult, onError);
	}

	checkPermission(); // start with checking permission

**Comment by canado** [comment]
Good morning, 

Thank you so much for the code.
I tried it ( I just replaced console.log by alerts );

_before I launch the app I activate the gps localisation._

then I have in this order

Permission not requested
Permission granted
geolocationError ( in my own function )
code:2
message: application does not have sufficient geolocation permissions.

: (

**Comment by canado** [comment]
Found it, the new pgb compiling setup is no more including location permissions in the androidmanifest !!!

Thanks again for the help, it's really appreciated.

**Comment by dpa99c** [comment]
Closing this on the basis that the solution is you should not use Phonegap Build
