### ISSUE TITLE
'IsGpsLocationEnabled()' not working

### ISSUE THREAD

**Issue by pyeonjaesik** [dpa99c/cordova-diagnostic-plugin#305]
'IsGpsLocationEnabled' is not working.
But if I install cordova-request-location -accuracy-plugin too, it works well.
However if I add cordova-plugin-fcm, I get build failed err. Following is my err that I have.
Execution failed for task ':app:processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 9.0.0.

---how to use IsGpsLocationEnabled() without cordova-request-location -accuracy-plugin? Or how to succeed building with cordova-request-location -accuracy-plugin?

Corova android platform is latest

**Comment by pyeonjaesik** [comment]
--Cordova android platform is latest

**Comment by dpa99c** [comment]
> 'IsGpsLocationEnabled' is not working.
> But if I install cordova-request-location -accuracy-plugin too, it works well.

The code of the two plugins is independent, so the presence of one cannot influence the outcome of the other.
Please try building and running the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) for this plugin to confirm this and that `IsGpsLocationEnabled()` is actually working fine with `cordova-android@7.1.0`.



> how to use IsGpsLocationEnabled() without cordova-request-location -accuracy-plugin? Or how to succeed building with cordova-request-location -accuracy-plugin?

This is due to a Gradle version collision  - see https://github.com/dpa99c/cordova-plugin-request-location-accuracy/issues/50 for a solution

**Comment by pyeonjaesik** [comment]
Thank you I'll try it

**Comment by pyeonjaesik** [comment]
I tried. 
cordova plugin add cordova-android-play-services-gradle-release  --variable PLAY_SERVICES_VERSION=15.+
cordova plugin add cordova-android-firebase-gradle-release  --variable FIREBASE_VERSION=15.+

But not working
