### ISSUE TITLE
iOS App rejection by simply adding the plugin, not using it, as of Jul 2018 (was fine before now)

### ISSUE THREAD

**Issue by pliablepixels** [dpa99c/cordova-diagnostic-plugin#317]
**I'm submitting a ...**  (check one with "x"):
- [ ] bug report
- [ ] feature request
- [x] documentation issue

**Environment information**

- Cordova CLI version 
        - `8.0.0`
- Cordova platform version
        - ` android 6.3.0`
        -  `ios 4.5.4`

- Plugins & versions installed in project (including this plugin)
        - `cordova.plugins.diagnostic 3.7.1`
        - other plugin versions not relevant to this issue
- Dev machine OS and version
```
    ProductName:	Mac OS X
    ProductVersion:	10.13.6
    BuildVersion:	17G65
```
        

# Documentation issue

### Summary
If you feel this is legit and if you've heard this recently from others, it might be a good idea to add this note to the [important notes](https://github.com/dpa99c/cordova-diagnostic-plugin#important-notes) section that it's highly recommended users only install the module(s) they want and ensure its usage is documented properly with app specific information (not a default "this app requires this function to work properly"). If a user were to install the whole thing, even if they _did_ document usage of the permissions they are using, the other permissions text would remain the default text and increase the chances of rejection in iOS.

### Details
I've had this plugin installed as part of my project for around a year now. I had intentions of using it but finally did not use it. I however, forgot to remove it. 

This caused no issues in either Play or App Store so far, for over 9 months. However, earlier this week (Jul 25), my iOS app was rejected with the message:

> We noticed that your app requests the user’s consent to access their Calendar, Motion Usage, Bluetooth Usage, Microphone, Contacts, Camera, Reminders but does not clarify the use of this feature in the permission modal alert.

If you [grep through my code](https://github.com/pliablepixels/zmNinja/search?q=diagnostic&unscoped_q=diagnostic), there isn't a single invocation of the diagnostic plugin (commented out for months now). So my app isn't really requesting any permissions (except for camera, which I document in my `config.xml`, and I don't use the diagnostic plugin here) but Apple's problem seems to be those keys exist in the plist.

After digging in, I found out that the plugin adds all these keys to Info.plist with a default description. 
Based on a previously closed issue, where you [mentioned](
https://github.com/dpa99c/cordova-diagnostic-plugin/issues/116#issuecomment-246998282) if you are not actually invoking it, there shouldn't be an issue, I think that might have recently changed.

I was on `3.7.x` branch so did not have the ability to select a specific module. I just discovered your `4.x` branch does just that, and I think users should be encouraged to only install the modules they need 

Thanks

**Comment by dpa99c** [comment]
Firstly, thanks for taking the time to report this.

My experience with the Apple app review process is that it's very inconsistent. I've had features in apps that have passed multiple reviews, then one time I release an update it gets rejected because that particular reviewer took issue with something that the other reviewers passed without comment. I've even had an app update rejected by Apple, created a new build with exactly the same codebase, submitted it for review and had it pass without issue.

However, I also understand that Apple move the goalposts when it comes to the criteria for app rejection. My experience has been that this is not necessarily related to changes in the guideline document which we all use as a reference, but due to changes in their internal app review criteria.

If your app has been rejected because of unused descriptions in the Info.plist, this is news to me. Prior to v4.x of this plugin, it included all the default descriptions (there were no modules) and I have had many apps pass review containing it, not to mention the large number of other devs using this plugin in their Cordova apps.

When I created v4 and divided the plugin into modules, I considered making the default behaviour of the plugin to install only the default core module. Instead I decided to make it backwardly-compatible to v3, etc. by installing all modules unless the preference in config.xml was specified. That was because I saw no reason to introduce breaking changes since as far as I was aware, having NSDescription's in the Info.plist was not a problem so long as you didn't call the relevant iOS permission request API that would result in the respective message being displayed.

Ultimately I was thinking to split this plugin into a series of multiple plugins where each module is a separate plugin which depends on the core plugin, e.g, `cordova-plugin-diagnostic-bluetooth` depends on `cordova-plugin-diagnostic-core`.

The short-term solution is to bump the plugin by a major version (v5) and make the default behaviour to install only the core module unless other modules are explicitly specified in the `config.xml`.

Do you think that would be a reasonable solution to this issue?

**Comment by pliablepixels** [comment]
Hello,

> If your app has been rejected because of unused descriptions in the Info.plist, this is news to me. Prior to v4.x of this plugin, it included all the default descriptions (there were no modules) and I have had many apps pass review containing it, not to mention the large number of other devs using this plugin in their Cordova apps.

1. Yes, I'm absolutely sure it was only because of this. I removed the plugin (and therefore the perms) and resubmitted it to Apple. No other changes. It was approved on Friday.

2. I also agree that many apps pass review containing it. Mine was one of them (for 9 months and many updates to the App Store in this duration), till this week. I suspect with the increased focus on GDPR and  user privacy, Apple is looking closer at these points. I was pointed to section 5.1.1 which is basically about privacy & permissions (been around for a while) including additional references to GDPR (which I am guessing is a more recent add on, haven't checked when it was introduced)

3. That being said, I don't know if this was a one-off or Apple will enforce this more universally. I suppose we will know  over time. The good part is since you have already broken things up with `v4` your plugin is ready for this. This is also why I only listed this as a documentation issue suggesting you consider referring to this possibility for this who add the full plugin and don't use all the features/don't change all the strings). On a completely different issue, I work on GDPR related compliancy in my day job, and I do know that "asking for permissions which are not necessary for the app" is also a violation of GDPR. So even if a user _were_ to diligently change all the text, Apple may just say "we really don't see where you are using any of these and why it is necessary" and reject. This is Apple, after all. The fact that the app is not really asking for them but it just happens to be listed as strings is technically valid, but again, this is Apple, after all.

With respect to your proposed solution, IMHO:

a) Till we know if this is a new apple review policy or not, its perfectly sensible to make v4 backward compatible with v3 so as not to confuse people.  I support your idea for v5 - architecturally, I do think it makes it clean.

b) You might consider,[ in the section](https://github.com/dpa99c/cordova-diagnostic-plugin#using-the-cordovaphonegapionic-cli) where you present an installation method to add the plugin with "all features" to put in a note somewhere that if Apple rejects the app and mentions permissions that you are sure your app is not using, it might be because of this issue and they may want to only install the plugins they need (and if their app were rejected and they are on a `3.x` branch, they should update to `4.x`). That being said, I understand this may create a concern when one may not be warranted (if my case is not normal), so I'll leave it to you to take a call.

If you feel we can now close this issue, as its intention (your attention and response) has been achieved, I'd be happy to close. Of course, if you would want to discuss anything else, perfectly fine too.

**Comment by dpa99c** [comment]
Let's close this for now until we know if your case was a one-off (Apple Reviewer having a bad day at work), but if you (or anyone else) experiences a rejection for similar reasons, I'll reopen so appropriate action can be discussed and taken.

**Comment by emeryg** [comment]
Hello,
I had the same issue yesterday: my app has been refused by Apple for the same reason.

Thanks

**Comment by dpa99c** [comment]
@emeryg Please can you paste the exact rejection message from Apple.

Also check which modules of this plugin you have specified in the `config.xml` preference and check that those were correctly applied when you built your project (i.e. the plugin source files for unspecified modules are not present in the Xcode project and the relevant `NSUsageDescription`'s are not present in the `*-Info.plist`.

**Comment by emeryg** [comment]
I was using the branch v3.x of your code, after having updated to the branch 4.x and use only the required modules, the problem seems to be solved.
Sorry about that.
Regards

---
The message from Apple :

Your app uses the "prefs:root=" non-public URL scheme, which is a private entity. The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change.

Continuing to use or conceal non-public APIs in future submissions of this app may result in the termination of your Apple Developer account, as well as removal of all associated apps from the App Store.

**Comment by askona** [comment]
@dpa99c Actually, adding description to config.xml doesn't solve the problem.
My ***.plist** file:
`<key>NSCameraUsageDescription</key>
<string>This app requires camera access to function properly.</string>
<key>NFCReaderUsageDescription</key>`
At the same time my **config.xml**
`<platform name="ios">
<allow-intent href="itms:*"/>
<allow-intent href="itms-apps:*"/>
<config-file parent="NSCameraUsageDescription" platform="ios" target="*-Info.plist">
<string>This app requires camera access to scan QR code </string>
</config-file>`

This is in case of build-from-scratch. (In my case I'm using Jenkins for automated builds)

BUT if I made any change to config.xml file, on next build cordova "detects" changes, and override NSCameraUsageDescription from config.xml to plist.
