### ISSUE TITLE
requestLocationAuthorization -ios

### ISSUE THREAD

**Issue by pyeonjaesik** [dpa99c/cordova-diagnostic-plugin#318]
**I'm submitting a ...**  (check one with "x"):
- [ o ] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**

   I want to call the function (requestLocationAuthorization) whenever I want to. Because My app require users' permission which is granted always not when in use. And If user choose when-in -use by mistake, I will ask permission again until users click granted. But Once I call the function, I dose not be called again.
no

**Expected behavior:**

**Steps to reproduce:**

**Environment information**

- Cordova CLI version 
	- `cordova -v` latest
- Cordova platform version
	- `cordova platform ls` 
- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`
- Dev machine OS and version, e.g.
    - OSX-latest
        
_Runtime issue_
- Device details
    -iPhone 6
	
_Android build issue:_	
- Node JS version
    - `node -v`
- Gradle version
	- `ls platforms/android/.gradle`
- Target Android SDK version
	- `android:targetSdkVersion` in `AndroidManifest.xml`
- Android SDK details
	- `sdkmanager --list | sed -e '/Available Packages/q'`
	
_iOS build issue:_
- Node JS version
    - `node -v`
- XCode version 9.4

**Comment by dpa99c** [comment]
The behaviour you describe is the intended behaviour Apple has implemented in iOS: if a user selects "When In Use" and you continue to ask permission again for "Always", Apple does not assume the user made a mistake in choosing "When In Use", they assume yours is a rogue app which would be harassing its users to allow location permission in the background when they may not want to allow it, so iOS prevents the location permission dialog being displayed again. Whether you agree with Apple or not is irrelevant since this is the behaviour that's hard-coded into iOS and there's no way around it.

**Comment by pyeonjaesik** [comment]
Thank you for advice. Than... How to change authorization mode not interrupting users? Such as  changing state from when-in-use to granted-always by users' one and simple click.

**Comment by dpa99c** [comment]
If you request "When In Use" and the user accepts, you can then request "Always" and the dialog will be shown. 

However, if you request "Always" and the user selects "When In Use", there's no way to show the dialog again or to do anything more than instruct your users to go to the Settings app and manually change the location permission setting for your app from "When In Use" to "Always".

**Comment by pyeonjaesik** [comment]
Thank you!

**Comment by preeti6695** [comment]
is there any way to do if user Don't allow permission ? can we ask again for permission to user?
