### ISSUE TITLE
Uh - oh error in MDAVSCLI after adding this plugin to Apache Cordova project (Asp.net)

### ISSUE THREAD

**Issue by vikas0vanvi** [dpa99c/cordova-diagnostic-plugin#32]
I have Apache Cordova project in VS 2013.5, I am trying to this plugin from config .xml and it gives build time error that 'Uh - oh' in MDAVSCLI .Any solution for this ?

**Comment by dpa99c** [comment]
Is there any more useful error output? "Uh - oh" doesn't really help much in identifying the cause...

e.g. what platform is causing this build error? Android? Windows?

To hazard a guess, are you building against Android API 23 using the main version of this plugin (i.e. `cordova plugin add cordova.plugins.diagnostic`)?

If not and you're building against an API version lower than 23, try using the API 22 version: `cordova plugin add cordova.plugins.diagnostic.api-22` - [see here](https://github.com/dpa99c/cordova-diagnostic-plugin#building-for-api-22-or-lower)

**Comment by vikas0vanvi** [comment]
hi , thanks for quick reply , yes i was building against an API of lower version , i will upgrade to Android API 23 and let you know if problem still persist

**Comment by vikas0vanvi** [comment]
hello , tried with Android API 23 but same issue , i am new to this so don't know much but i found one link by googling he had same issue and there are screen shots too , i am facing same after adding this plugin if you can take look and guide it will be very helpful , here's link 
https://github.com/litehelpers/Cordova-sqlite-storage/issues/237

**Comment by dpa99c** [comment]
The cordova-sqlite-storage issue you linked to involves building for Windows Phone 8.x, whereas, as I understand it, your issue is with building the Android platform. Given that the error message is 'Uh - oh' in MDAVSCLI, I would guess that could have many causes.

In addition to upgrading to API 23, have you also installed the pre-requisite Android libraries that are required for Android 6 runtime permissions, as [documented here](https://github.com/dpa99c/cordova-diagnostic-plugin#important-android-note)?

Alternatively, if you don't explicitly need to use Android 6 runtime permissions, you can, as I said above, use the [API 22 branch of the plugin](https://github.com/dpa99c/cordova-diagnostic-plugin/tree/api-22) (it will of course also build with API 23):

    cordova plugin add cordova.plugins.diagnostic.api-22

**Comment by vikas0vanvi** [comment]
yes tried that yesterday with cordova CLI but its giving 
Error: 404 Not Found: cordova.plugins.diagnostic.api-22

**Comment by dpa99c** [comment]
It's [here on npm](https://www.npmjs.com/package/cordova.plugins.diagnostic.api-22) and installs fine with cordova-cli@5.4.1:
![api-22](https://cloud.githubusercontent.com/assets/2345062/12749070/3d808632-c9a6-11e5-8422-dc99f1b59477.jpg)

If you're having issues with npm, you can also install it direct from the branch in github:

    cordova plugin add https://github.com/dpa99c/cordova-diagnostic-plugin#api-22

**Comment by vikas0vanvi** [comment]
thank you very very much , finally that worked !! a big relief :) 
i really appreciate for spending your valuable time

**Comment by dpa99c** [comment]
glad you got it working :+1:
