### ISSUE TITLE
Location module requires "always" permissions on iOS

### ISSUE THREAD

**Issue by sertal70** [dpa99c/cordova-diagnostic-plugin#328]
**I'm submitting a ...**  (check one with "x"):
- [X] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**
When the LOCATION  module is added on iOS platform the following permissions are always required:

- NSLocationWhenInUseUsageDescription
- NSLocation**Always**AndWhenInUseUsageDescription
- NSLocation**Always**UsageDescription

but there are many scenarios in which the app does not require location informations "always" (that is when in background mode), so the plugin should give the user the option to specify which type of location information the app need.

This behaviour happens always when the location module is loaded in the plugin.

**Expected behavior:**
I would expect to have options to control which features of location module I need to be included in the app.

**Steps to reproduce:**

**Environment information**

- Cordova CLI version 
7.1.0
- Cordova platform version
   - android 6.4.0
   - ios 4.5.5

- Plugins & versions installed in project (including this plugin)
   - cordova.plugins.diagnostic": "4.0.10"

_iOS build issue:_
- Node JS version
    - v8.9.3
- XCode version
   - 10.0

- Ionic environment info
    - `cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.1.1 (cordova-lib@8.1.0)

local packages:

    @ionic/app-scripts : 3.2.0
    Cordova Platforms  : android 6.4.0 ios 4.5.5
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-sim           : 5.0.13
    Node              : v8.9.3
    npm               : 5.10.0
    OS                : macOS High Sierra
    Xcode             : Xcode 10.0 Build version 10A255

Environment Variables:

    ANDROID_HOME : /Users/Sergio/Library/Android/sdk

Misc:

    backend : legacy`
- Installed Ionic Native modules and versions
    - `├── @ionic-native/device@4.3.3
├── @ionic-native/diagnostic@4.15.0
├── @ionic-native/email-composer@4.3.3
├── @ionic-native/file@4.3.3
├── @ionic-native/geolocation@4.3.3
├── @ionic-native/http@4.3.3
├── @ionic-native/in-app-browser@4.3.3
├── @ionic-native/keyboard@4.15.0
├── @ionic-native/media@4.3.3
├── @ionic-native/network@4.3.3
├── @ionic-native/push@4.12.0
├── @ionic-native/social-sharing@4.12.0
├── @ionic-native/splash-screen@4.3.3
├── @ionic-native/status-bar@4.3.3`

**Comment by dpa99c** [comment]
This plugin [injects default placeholders](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/plugin.xml#L60) for the `NSLocationAlways` keys into the `*-info.plist` which can be overridden by app-specific messages defined in the `config.xml`.

Their presence in the `*-info.plist` does not mean location "always" permission is implicilty requested by the the app; these messages are only displayed if you actually request location "always" permission at runtime, i.e.:

	cordova.plugins.diagnostic.requestLocationAuthorization(onSucces, onError, cordova.plugins.diagnostic.locationAuthorizationMode.ALWAYS);

If you only request location "when in use" permission, the messages in the `NSLocationAlways*UsageDescription keys will never be used/displayed to the user.

The reason all `NSLocation*UsageDescription` keys are added by default is because if they are not present in the `*-info.plist` and the app contains the native iOS calls to the corresponding Location Manager functions (which [this plugin of course does](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/src/ios/Diagnostic_Location.m#L84)), then when you attempt to upload your app binary to App Store Connect, it will be automatically rejected with the message:

> This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSLocationAlwaysUsageDescription key with a string value explaining to the user how the app uses this data.

In addition, if you try to request location "always" permission at runtime without `NSLocationAlways*UsageDescription` keys present in the `*-info.plist`, the app will (natively) crash with an exception.

**Comment by sertal70** [comment]
Thank you @dpa99c for you answer, very clear.

As I said previously, my app does not use location "always" but the fact the plugin (potentially) does implies I have to declare in the `*-info.plist`. 

From my point of view ideal would be have location module split in two parts, so that location "always" could be included only in those projects that really need it. This would avoid to mandatory declare "always" permission in the `*-info.plist` in projects that don't use them. 

Principle is: less things you put in, less things Apple can complain against, you know. Nowadays also privacy is a big concern, so our projects should include the minimum necessary permissions to maintain the trust with the user.
