### ISSUE TITLE
Unable to get SD Card path with getExternalSdCardDetails on Android 5.1

### ISSUE THREAD

**Issue by tejpochiraju** [dpa99c/cordova-diagnostic-plugin#332]
**I'm submitting a ...**  (check one with "x"):
- [x] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**

getExternalSdCardDetails() works as expected on Android 6 and newer. However, SD card details are not returned on Android 5.1. Tested with the [Ionic Diagnostic Example App](https://github.com/dpa99c/cordova-diagnostic-plugin-ionic-example) too.

**Expected behavior:**

Should return SD Card details as documented in the README.

**Steps to reproduce:**
Build the [example app](https://github.com/dpa99c/cordova-diagnostic-plugin-ionic-example) and run on Android 5.1 or otherwise attempt to use getExternalSdCardDetails().

**Environment information**

- Cordova CLI version 
	- 8.0.0
- Cordova platform version
	- Android 7.0.0
- Plugins & versions installed in project (including this plugin)
    - NA
- Dev machine OS and version, e.g.
    - OSX
        - 10.14
        
_Runtime issue_
- Device details
    - Intex Aqua 
- OS details
    - _Android 5.1.1_	
	
_Android build issue:_	
- Node JS version
    - v8.11.4
- Gradle version
	- 4.9
- Target Android SDK version
	- 23
- Android SDK details
	- 23, 24, 26 and 28 installed

_If using an [Ionic Native Typescript wrapper]() for this plugin:_
- Ionic environment info
    - 4.3.1

**Comment by dpa99c** [comment]
This plugin [uses several methods to attempt to locate external removable media](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/src/android/Diagnostic_External_Storage.java#L196).
For Android 5.1.1, [it's primary method](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/src/android/Diagnostic_External_Storage.java#L213) will be to use the [Environment.isExternalStorageRemovable()](https://developer.android.com/reference/android/os/Environment#isExternalStorageRemovable()) method.
If the device is returning no data for `getExternalSdCardDetails()`, it's likely that's because the above method is not returning results.

The problem here is more likely to be the device that the Android version.
External removable storage was never standardized by Google so different hardware vendors implemented it in different ways. 
The "Intex Aqua" is a fairly uncommon device globally (in fact it's confined to India) so it's likely they have used a bespoke implementation for the external removable SD card.

To confirm my above assumption, I would ask you (if possible and you haven't already done so) to test on a "Intex Aqua" with Android 6+ vs Android 5.1.1


Please also post the actual filepath of the external removable SD card on the device which is encountering the issue (e.g. `/storage/extSdCard`).

**Comment by dpa99c** [comment]
Closed due to no response

**Comment by tejpochiraju** [comment]
Apologies for the delay. We are unable to test it on Android 6 using the same device as we do not have the ability to roll back and we need this for testing apps against 5.1.

We were able to get this working by:

1. Attempt to get path with the Diagnostic plugin
2. If the path comes back empty, offer a text input field prefilled with e.g. "/storage/sdcard1/"
3. Prompt the user to use a specific file manager to find out this path and type it in.

This works for now as this app is 'commissioned' by a deployment team for users using the SD card variant.

We will try to dig a little deeper when we get a chance to figure out why this failed in the first instance.

**Comment by dpa99c** [comment]
Thanks for the update.

So was the path to the external SD card on this particular device (with Android 5.1) `/storage/sdcard1/`?

I'm thinking that a possible enhancement that could be added to this plugin is, if the current methods fail to find any results, to try accessing a list of known hard-coded paths such as  `/storage/sdcard1/`, `/storage/extSdCard`, etc.
