### ISSUE TITLE
iPhone4  iOS 7.1.2 Crash

### ISSUE THREAD

**Issue by mjnf** [dpa99c/cordova-diagnostic-plugin#34]
Hello,

I have a crach in iPhone4 and iPhone4s  iOS 7.1.2. I can reproduce 100% on call cordova.plugins.diagnostic.switchToSettings. In other devices is working perfect. I'm using Phonegap Build.

Thanks !

**Comment by dpa99c** [comment]
`switchToSettings()` will not work on iOS 7 and below, because Apple didn't add the necessary functionality until iOS 8. The plugin [performs a check](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/src/ios/Diagnostic.m#L338) to ensure the functionality is present before invoking it ([see here](http://stackoverflow.com/a/26914817/777265)), so on iOS 7 and below it should invoke the error callback.
However, I don't have a device running iOS 7 or below, and these old versions are not available as Simulators in Xcode 7, so I'm unable to test this.

> I have a crach in iPhone4 and iPhone4s iOS 7.1.2. 

By this, do you mean the app actually crashes (exits) or that the error handler is being invoked (as expected)?

**Comment by mjnf** [comment]
Hi @dpa99c,

The application crash when call switchToSettings, is not handler the error. I can try, handler the error in JS without lucky. I will add a validation in my side. Thanks !

**Comment by dpa99c** [comment]
Didn't mean to close it yet :-) 

@mjnf  Any chance you could check that this resolves the problem on <= iOS 7?
I don't have an iOS 7 device and XCode no longer provides it in a simulator...

The fix is on the master branch:

    cordova plugin add https://github.com/dpa99c/cordova-diagnostic-plugin

**Comment by dpa99c** [comment]
Then I will close it
