### ISSUE TITLE
iOS requestLocationAuthorization's success callback executes immediately

### ISSUE THREAD

**Issue by zarko-tg** [dpa99c/cordova-diagnostic-plugin#35]
User if this is a bug or a problem with the wording in the documentation.

The success callback function of requestLocationAuthorization is being called immediately / as soon as the dialog is shown on iOS. My expectation is that it must be called once the user allows usage of device location, as it already does so on Android.

Experienced on a iOS 9.3 iPhone 6.

**Comment by dpa99c** [comment]
I need to make this clearer in the documentation.

On Android (6+), `requestLocationAuthorization(success, error)` is an alias for:

    Diagnostic.requestRuntimePermissions(success, error, [
        Diagnostic.runtimePermission.ACCESS_COARSE_LOCATION,
        Diagnostic.runtimePermission.ACCESS_FINE_LOCATION
    ]);

Hence the success callback is invoked in response to the user's choice in the dialog and is passed the resulting outcome.

On, iOS it works differently: when `requestLocationAuthorization()` is called, the resulting dialog is invoke on a different thread. In order to listen for the response, you currently need to use [registerLocationAuthorizationStatusChangeHandler()](https://github.com/dpa99c/cordova-diagnostic-plugin#registerlocationauthorizationstatuschangehandler), which is invoked in response to a change in authorisation status. So on iOS, the `requestLocationAuthorization()` success callback is invoked on successfully making the request, not in response to the user's choice in the dialog.

In the short term, I'll update the docs. In the longer term, I'll see if I can do away with registerLocationAuthorizationStatusChangeHandler() on iOS and simply have the success function of requestLocationAuthorization() be called after the user has made their choice (same as Android).
