### ISSUE TITLE
READ_CALL_LOG denied_always

### ISSUE THREAD

**Issue by mtnskb** [dpa99c/cordova-diagnostic-plugin#377]
i'm trying to request the READ_CALL_LOG for access to incoming call number. I need this permissions in Android 9 because without it the incoming number is empty. 
The request doesn't show the dialog to accept or decline the permission, only return denied always. The application haven't any permission blocked. With READ_PHONE_STATE is working fine.

In getPermissionAuthorizationStatus the status is NOT_REQUESTED...

Any idea?

thanks

**Comment by dpa99c** [comment]
`READ_CALL_LOG` is one of a handful of special permissions, which due to the sensitive nature of the data they grant access to, have special requirements as [outlined here](https://play.google.com/about/privacy-security-deception/permissions/):

> Your app manifest requests the Call Log permission group (e.g. READ_CALL_LOG, WRITE_CALL_LOG, PROCESS_OUTGOING_CALLS)
> It must be actively registered as the default Phone or Assistant handler on the device.

So unless you register you app as the default Phone or Assistant handler on the device, Android will always deny your app permission.


Also ensure you've added `<uses-permission android:name="android.permission.READ_CALL_LOG" />` to your `AndroidManifest.xml`
