### ISSUE TITLE
Adding new permissions check ?

### ISSUE THREAD

**Issue by Durss** [dpa99c/cordova-diagnostic-plugin#38]
Hello !

First of all, thank you (again) for that good job !
It works like a charm and it works around all the plugins not up to date with android 6 permissions system !

Still it could be an even more "ultimate" plugin if other permissions types were also implemented.
For example :
 * Contacts access
 * SMS access
 * Calendar access
 * Microphone access
 * Sensors access

This is of course just a suggestion, it's already pretty cool to have what you already did :)
I just wish i had more native coding knowledge to help you insteady of just suggesting/requesting things..

Anyways,
Thank you again for sharing your work !

Have a good day !

**Comment by dankito** [comment]
I also like to vote for the Microphone access enhancement.

On Android it could be done via
   cordova.plugins.diagnostic.getPermissionAuthorizationStatus(successCallback, errorCallback, "RECORD_AUDIO")
.

On iOS, at least starting with iOS 8, with
    [AVAudioSession sharedInstance].recordPermission
. The return value is of type AVAudioSessionRecordPermission:

enum {
   AVAudioSessionRecordPermissionUndetermined     = 'undt',
   AVAudioSessionRecordPermissionDenied           = 'deny',
   AVAudioSessionRecordPermissionGranted          = 'grnt'
};
typedef NSUInteger  AVAudioSessionRecordPermission;

Would love to see it in your plugin.

And just as Durss said: Thanks for sharing for work! It's a great plugin.

**Comment by roblav96** [comment]
This plugin is incredible! Please add contacts permissions :D

**Comment by dpa99c** [comment]
As of v3.0.0, the plugin now supports:

* Contacts access
* Calendar access
* Microphone access


With regard to the other permissions mentioned:

**SMS access** This is only possible on Android (not on iOS). This can already be achieved on Android (6) by using the plugin to request a runtime permission from the SMS permissions group (e.g. `SEND_SMS`) using [requestRuntimePermission()](https://github.com/dpa99c/cordova-diagnostic-plugin#requestruntimepermission)

**Sensors access** I take this to refer to "Health Sensors", referred to on Android as "Body Sensors" and iOS as "Health". 

On Android (6), this run-time permission can be granted by requesting `BODY_SENSORS` using [requestRuntimePermission()](https://github.com/dpa99c/cordova-diagnostic-plugin#requestruntimepermission)

For iOS, requesting HealthKit permissions is far from trivial. Permission must be requested individually for each data type and a corresponding custom message key added to the list plist for each. See the [HealthKit docs](https://developer.apple.com/library/ios/documentation/HealthKit/Reference/HealthKit_Framework/) for more detail. Since there a dozens of possible HealthKit measurement types ([see here](http://stackoverflow.com/questions/30856944/healthkit-data-types-overview/30868219#30868219)), this isn't functionality that can be easily/quickly incorporated into this plugin, hence for now at least, I won't be adding support for it.

Closing this issue now as all the original permissions requested have been addressed above. Any requests for managing additional types of permissions can be opened as a new issue.
