### ISSUE TITLE
Failed to execute aapt

### ISSUE THREAD

**Issue by chetan549** [dpa99c/cordova-diagnostic-plugin#390]
Hi after installing this plugin in my ionic 3 project i am getting  Failed to execute aapt error but when i remove this plugin the error escapes. plz tell the solution

**Comment by dpa99c** [comment]
This is not enough information to investigate the issue. The error could be caused by a conflict with another plugin or numerous other possible causes.

Please test using the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) as a known working reference and if you are able to reproduce the issue there, please open a new issue and complete the issue template with all relevant information.
