### ISSUE TITLE
How check after switchToLocationSettings()

### ISSUE THREAD

**Issue by paulogr** [dpa99c/cordova-diagnostic-plugin#4]
Hi,

How do you guys do to check if location was enabled after switch to location settings screen?

Because the user could just get back to the app without enable the GPS right? We have to check again and again until have sure that is enable.

Maybe if switchToLocationSettings returns a promise... I don't know

How did you solve that?

Thank you!

**Comment by dpa99c** [comment]
I could extend switchToLocationSettings to support a Javascript success callback, however when switchToLocationSettings() is called, the Cordova app is switched out into the background when the settings app is switched into the foreground, so the callback wouldn't be executed until the Cordova app is resumed. And in which case, you may as well re-check the location settings when the Cordova app is resumed; this will then also work if the user manually puts your app in the background (e.g using Home button), changes the location settings then returns to your app (this is the approach I've used in my apps).

For example:

    var locationEnabled;
    function checkLocationState(){
        cordova.plugins.diagnostic.isLocationEnabled(function(enabled){
            locationEnabled = enabled;
        }, onError);
    }
    document.addEventListener('resume', checkLocationState, false);
    document.addEventListener('deviceready', checkLocationState, false);

Note that on Android it's possible to change location settings without putting the app into the background using the quick settings menu via the status bar pull down. Because the app remains in the foreground, the resume event is not fired, so your app may remain unaware of the change. The approach I've taken in my apps is to re-check the location settings state after the first call to the positionError handler function for navigator.geolocation.watchPosition. This way, if the user turns off location settings while the app is in the foreground, the positionError handler will be called and my app will pick up the changed setting.

**Comment by dpa99c** [comment]
Is this still an issue or can it be closed?

**Comment by Shakti-Sharma** [comment]
On hitting back button  from location screen button, does not trigger any resume and deviceready event, Event i didnt get call back 



  cordova.plugins.diagnostic.switchToLocationSettings(function(success){
                console.log(success);


            }, function(error){
                console.error("The following error occurred: "+error);

            });


It is not solved yet

**Comment by Shakti-Sharma** [comment]
![screenshot_20161129-193150-1](https://cloud.githubusercontent.com/assets/4133139/20712735/66893a6c-b66b-11e6-9153-76f8906533fd.png)


Following back button in the bottom will be tigger any thing. 
How to i handle it that the back button is pressed.

resume and deviceready event is not fired on hitting the back button.


Please Help.

**Comment by Shakti-Sharma** [comment]
@paulogr Plz help and open this issue.

**Comment by dpa99c** [comment]
@Shakti-Sharma This issue is resolved: as explained above, the `switchToLocationSettings()` function **does not** accept a callback function as a parameter due to the fact that the app will be immediately paused when the function is called, so the callback would not be executed until the app is resumed. And therefore, you may as well use the Cordova "resume" event to be notified. Using the back button in Android to return to the app **does** cause Cordova to fire the "resume" event as Android restores the activity to the foreground. For reference, please see the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) which [makes use of the resume event in this way](https://github.com/dpa99c/cordova-diagnostic-plugin-example/blob/master/www/js/index.js#L572).

**Comment by Shakti-Sharma** [comment]
I tried 

var locationEnabled;
function checkLocationState(){
    cordova.plugins.diagnostic.isLocationEnabled(function(enabled){
        locationEnabled = enabled;
    }, onError);
}
document.addEventListener('resume', checkLocationState, false);
document.addEventListener('deviceready', checkLocationState, false);

but on coming back it does not trigger the resume event.


Now for the purpose of solution, i am putting a hack, like adding a timer in the app to check wheather location is on or not.

I am using ionic framework

Regard
Shakti

**Comment by sidgujrathi** [comment]
I am having same issue with iOS, I am listening for both "resume" and "deviceReady" events but none of the are triggered if user uses back button from settings, although it does triggered if users go to recent app and then selects app.

**Comment by littlegit** [comment]
Solution: https://www.npmjs.com/package/cordova.plugins.diagnostic#registerlocationstatechangehandler

**Comment by carherco** [comment]
@littlegit That was the solution. Thanks!!!!

**Comment by kapilSoni101** [comment]
@littlegit  sir i will check but after click mobile back button registerLocationStateChangeHandler is not trigger in my case ?
