### ISSUE TITLE
2.3.11 Camera Permissions

### ISSUE THREAD

**Issue by adru** [dpa99c/cordova-diagnostic-plugin#41]
https://github.com/dpa99c/cordova-diagnostic-plugin/commit/2abb480ddaac5a6f0e08a19739cf5f0598dabd82

Removal of Camera permission line prevents apps from requesting access for Camera support.
It only requests Storage. All of the status checks for Camera then return GRANTED but checking the App settings, Camera is not, only Storage.
Specifying 2.3.10 in phonegap fixes issue.

I’m not sure if it’s only my phone, tested on Android 6.0, HTC One M8.

**Comment by dpa99c** [comment]
Due to [this bug](https://issues.apache.org/jira/browse/CB-10120) in cordova-plugin-camera, Camera permission actually causes the camera activity of cordova-plugin-camera to crash if it's denied. That plugin actually only needs Storage permission, not Camera. So pull request #33 removed the request for Camera from the Android variant of `requestCameraAuthorization()`, since this method is primarily aimed at being used in conjunction with cordova-plugin-camera.

If you need to request Camera permission explicitly, you can do so using `requestRuntimePermission()`:

    cordova.plugins.diagnostic.requestRuntimePermission(successFn, 
        errorFn, 
        cordova.plugins.diagnostic.runtimePermission.CAMERA
    );

I'll update the documentation to explain this.

**Comment by dpa99c** [comment]
Just seen that [the Cordova bug](https://issues.apache.org/jira/browse/CB-10120) [has been fixed](https://github.com/apache/cordova-plugin-camera/commit/0cd962466d2641fcd05155690e23432db02cc79a) on the [master branch of cordova-plugin-camera](https://github.com/apache/cordova-plugin-camera) which is currently on `v2.1.2-dev`. 

That fix causes `CAMERA` permission to be requested again, which means that this plugin can happily request it again also, without feature of breaking the Camera plugin. 
However, I will only apply this once `cordova-plugin-camera@2.1.2` is published as a release - [current version on npm](https://www.npmjs.com/package/cordova-plugin-camera) is `2.1.1` which still breaks if `CAMERA` permission has been requested.

So for now, I'll document that `requestCameraAuthorization()` doesn't request `CAMERA` but when `cordova-plugin-camera@2.1.2` is published as a release, I'll update this plugin to request `CAMERA permission again`
