### ISSUE TITLE
Looks like your plugin doesn't work with camera at all 

### ISSUE THREAD

**Issue by frontenddeveloping** [dpa99c/cordova-diagnostic-plugin#412]
5.0.2 version on real device always says that:
- Camera was not granted
- Status is false and etc

Build with 6.0.2 version always failed

Cordova - 9.0.0 (cordova-lib@9.0.1)

**Comment by dpa99c** [comment]
It's not possible to diagnose your exact issue since you failed to complete the issue template, but I would speculate you did not add the required permissions to the `AndroidManifest.xml` as specified in the documentation.

Please read the documentation carefully and run the [example project app](https://github.com/dpa99c/cordova-diagnostic-plugin-example) to validate the plugin functionality.
