### ISSUE TITLE
[Docs] NOT_DETERMINED is not an authorization status

### ISSUE THREAD

**Issue by NoelDeMartin** [dpa99c/cordova-diagnostic-plugin#413]
In various authorization request methods there is a note for iOS saying "This should only be called if authorization status is NOT_DETERMINED".

However, `NOT_DETERMINED` is not a valid [iOS authorization status](https://github.com/dpa99c/cordova-diagnostic-plugin#ios). It's only documented as a motionStatus.

**Comment by dpa99c** [comment]
Thanks for the correction. This documentation error is due to out-of-date docs arising from this plugin's subsequent abstractration of platform-specific differences:

The native iOS implementation [uses constants](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/src/ios/Diagnostic_Location.m#L176) such as [`kCLAuthorizationStatusNotDetermined`](https://developer.apple.com/documentation/corelocation/clauthorizationstatus/kclauthorizationstatusnotdetermined?language=objc), whereas [`NOT_REQUESTED`](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/src/android/Diagnostic.java#L508) is the logical state in native Android code.

The plugin attempts to unify the platforms with a [Javascript mapping of `not_determined` to `NOT_REQUESTED`](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/www/ios/diagnostic.js#L24) on iOS.
However, in old plugin versions they were separate platform-specific constants so the documentation has got out-of-date with respect to the implementation.

**Comment by dpa99c** [comment]
Resolved by #414
