### ISSUE TITLE
getBluetoothState() returns UNKNOWN the first time (duplicate)

### ISSUE THREAD

**Issue by SamuelMichelRiad** [dpa99c/cordova-diagnostic-plugin#439]
This is a duplicate of #271, which is closed. This is still happening in version 6.0.3. Any pointers?

**Comment by 192kobayashi** [comment]
me too.

cordova-cli: 10
cordova-ios: 6.2.0
cordova-diagnostic-plugin: 6.1.0

Am I doing something wrong??

**Comment by dpa99c** [comment]
The first time you call `getBluetoothState()` on iOS, it [initialises the native Bluetooth Manager](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/src/ios/Diagnostic_Bluetooth.m#L150).
When the native manager is initialised, it starts in an `UNKNOWN` state then resolves to `POWERED_ON`, `POWERED_OFF` etc.
So the best thing to do it use [registerBluetoothStateChangeHandler()](https://github.com/dpa99c/cordova-diagnostic-plugin#registerbluetoothstatechangehandler) to register a listener function to receive the various state changes that are broadcast by the native manager when it starts up.

The reason that this plugin doesn't immediate initialise the native manager upon app startup, but instead waits for the first call to `getBluetoothState()`, is that initialising the native Bluetooth manager implicitly triggers a Bluetooth permission request dialog if Bluetooth permission is not already granted. This would mean that your app would immediately show the native permission dialog on first run with no explanation.

Therefore you should wait until Bluetooth permission has been explicitly requested by the app using `requestBluetoothAuthorization()` and has been granted by the user (you can monitor this in you own local persistent app state) before calling `getBluetoothState()` since this will implictly make the permission request.
And to monitor the flow of state changes in the native manager, use `registerBluetoothStateChangeHandler()`.

I understand this is not ideal but the logic this plugin can implement is limited by the quirks of the underlying implementation of the native Bluetooth manager API in iOS.
Therefore I'm closing this because I don't see a way that the plugin can better handle the unintuitive nature of the native Bluetooth manager API on iOS.
