### ISSUE TITLE
the CameraAuthorization is wrong

### ISSUE THREAD

**Issue by wzhsh90** [dpa99c/cordova-diagnostic-plugin#44]
in your example the diagnostic.js 
Diagnostic.requestCameraAuthorization = function(successCallback, errorCallback){
		Diagnostic.requestRuntimePermission(successCallback, errorCallback, Diagnostic.runtimePermission.CAMERA);
	};
is right,but when we use cordova insall the plugin the method is 
	Diagnostic.requestCameraAuthorization = function(successCallback, errorCallback){
		function onSuccess(statuses){
			successCallback(combineCameraStatuses(statuses));
		}
		Diagnostic.requestRuntimePermissions(onSuccess, errorCallback, [
			Diagnostic.runtimePermission.READ_EXTERNAL_STORAGE
		]);
	};

is that paste wrong ???

**Comment by dpa99c** [comment]
The current behaviour of `requestCameraAuthorization()` is correct in that it requests `READ_EXTERNAL_STORAGE`, because this is the only permission required by the current version of [cordova-plugin-camera](https://github.com/apache/cordova-plugin-camera).

See the [Android Camera permissions](https://github.com/dpa99c/cordova-diagnostic-plugin#android-camera-permissions) section in the documentation for more details.

**Comment by wzhsh90** [comment]
ok,thank you I get it. the example apk requested CAMERA not  READ_EXTERNAL_STORAGE

**Comment by dpa99c** [comment]
I probably haven't rebuilt the example APK recently. I'll add it my todo list. Sorry for the confusion.
