### ISSUE TITLE
IOS location services

### ISSUE THREAD

**Issue by minghwee** [dpa99c/cordova-diagnostic-plugin#470]
Hi

Many thanks for the great work you have there!

Would like to check if there is any specific reason on why isGpsLocationEnabled() is not available for IOS and it is only available for Android?
Will using isLocationEnabled() be the equivalent for IOS? also isGpsLocationEnabled() will it return true for both GPS and Network location?
Also what would be the expected behavior if we use a plugin which is not available for the specific platform as I would like my app to be available in both IOS and Android
? e.g. having isGpsLocationEnabled() when I'm building for IOS. Will it simply skip it or returns a failed promise?

Thanks and Regards

**Comment by dpa99c** [comment]
> Would like to check if there is any specific reason on why isGpsLocationEnabled() is not available for IOS and it is only available for Android?

Because the native Android location manager API provides methods which differentiate between GPS vs network location but iOS location manager does not.

> Will using isLocationEnabled() be the equivalent for IOS? 
iOS internally manages location services and opaquely uses both GPS and network location.

So yes, `isLocationEnabled()` will return true if iOS is using either GPS or network location to determine current location.


> also isGpsLocationEnabled() will it return true for both GPS and Network location?

yes, the plugin will return true if both GPS and Network location are enable but not if only network (but not GPS) location is enabled - [see here](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/src/android/Diagnostic_Location.java#L186)


> Also what would be the expected behavior if we use a plugin which is not available for the specific platform as I would like my app to be available in both IOS and Android
> ? e.g. having isGpsLocationEnabled() when I'm building for IOS. Will it simply skip it or returns a failed promise?

Platform-specific functions such as `isGpsLocationEnabled()` are only defined in the JS API for the relevant platform.
So if you call `isGpsLocationEnabled()` on iOS, you'll get a JS error because it's not defined.
So you should check which platform you are running on before calling a platform-specific function.
