### ISSUE TITLE
switchToSettings() in iOS 

### ISSUE THREAD

**Issue by MrPerfect0** [dpa99c/cordova-diagnostic-plugin#475]
I used switchtosettings() function for my location service enhancement but it open/redirect to the main settings page instead of app setting page in some ios devices. eg. Iphone 11 Pro.

Is tht anything I need to take note? because as i knw its a single line code which all device should open the app settings page.

**Comment by dpa99c** [comment]
The plugin's [iOS implementation of `switchToSettings()`](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/src/ios/Diagnostic.m#L58) invokes the standard iOS API method [UIApplicationOpenSettingsURLString](https://developer.apple.com/documentation/uikit/uiapplicationopensettingsurlstring?language=objc) which deep links to the app settings page. 
There is no other iOS API method available to perform this operation so if it is misbehaving this is due to its implementation in the iOS SDK which this plugin has no control over.
