### ISSUE TITLE
Success callback for request location fires before user choice on iOS

### ISSUE THREAD

**Issue by j-ro** [dpa99c/cordova-diagnostic-plugin#49]
using cordova.plugins.diagnostic.requestLocationAuthorization() on iOS, cordova 6.1.1 -- the success callback fires when the function is called, not when the user picks a choice, meaning I still must use the event listener to actually get user choice.

**Comment by dpa99c** [comment]
Check you are using the most recent version of the plugin: this issue was fixed in v2.3.12 in response to #35 by commit 1636f3cb2d42b75e28e44fbd78f824913f04f778.
I have tested `cordova.plugins.diagnostic.requestLocationAuthorization()` on iOS 9 using the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example), so if you continue to have issues, try building and running this for comparison.

**Comment by dpa99c** [comment]
Reopen if still an issue
