### ISSUE TITLE
No working POST_NOTIFICATIONS

### ISSUE THREAD

**Issue by SinGlEBW** [dpa99c/cordova-diagnostic-plugin#493]
cordova -v: 11.0.0
 "android-minSdkVersion" value="22"
 "android-targetSdkVersion" value="31" 
 "android-compileSdkVersion" value="31"

       
        Does not output Permission
        diagnostic.requestRuntimePermission((status) => { console.log(status) }, () => {}, diagnostic.permission.POST_NOTIFICATIONS)

**Comment by dpa99c** [comment]
If you don't implement the error callback, you won't know if the reason that the success callback is not being called is because the error callback is: `() => {}`
Check you have added the permission to your manifest, build and run the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) to validate your development environment

**Comment by mirko77** [comment]
POST_NOTIFICATIONS always returns DENIED_ALWAYS when targeting API 33 in Android 11, even when the notification permission is granted.

Works in Android 13 API 33, no problems

**Comment by dpa99c** [comment]
I can reproduce the same outcome: building with API 33 on device running Android 11, the permission result from Android is `DENIED` for `POST_NOTIFICATIONS`. 
You'd think the correct response from Android would be `GRANTED` since it's implicitly granted since Android 11 doesn't implement `POST_NOTIFICATIONS` as a run-time permission.
I'll update the plugin code to handle this correctly.
