### ISSUE TITLE
Cordova diagnostic + Crosswalk

### ISSUE THREAD

**Issue by norvinjohn** [dpa99c/cordova-diagnostic-plugin#50]
Hi everyone,

Just a quick question did any body of you encountered a build error after installing crosswalk + cordova diagnostic.

Or do you know any other plugin that I can use to enable gps/location.

Happy Coding <3 :D

**Comment by gsanjeevkumar** [comment]
no have not received any so far.

**Comment by dpa99c** [comment]
@norvinjohn I honestly haven't tried building it with crosswalk, but if you're encountering build errors, please post as many details as possible, including full error output, versions of cordova/plugin/platform, build environment, test OS/devices, etc.

**Comment by norvinjohn** [comment]
Sorry I did not mention that I was developing using ionic.
I used the "ionic browser add crosswalk" command to install crosswalk.

Development environment:

Cordova CLI: 5.3.3
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.4 LTS 
Node Version: v4.4.0

OS/device:
android 4.4.4

![screenshot from 2016-04-13 05 46 08](https://cloud.githubusercontent.com/assets/6295837/14477102/6c845bd2-013e-11e6-922c-2c0d0083e614.png)
![screenshot from 2016-04-13 05 46 43](https://cloud.githubusercontent.com/assets/6295837/14477104/6e727a82-013e-11e6-94b6-e5c77fd6e5c9.png)

**Comment by dpa99c** [comment]
From the error message, it looks like v22 of the Android support library is being included into a build targeting API 23. This plugin requires v23+ of the support library in order to support Android runtime permissions.

Firstly, check the version of the cordova-android platform installed into the project:

    cordova platform ls

If it's less than 5.0.0, this is the cause of your problem: you'll need to remove it (`cordova platform rm android`) and explicitly add v5.0.0 (`cordova platform add android@5.0.0`).

Otherwise, open the Android SDK manager and check that Android Support Library (under Extras) is at least 23.

I've no experience of building Cordova on Ubuntu, but from your log output it looks suspiciously like the android support library is being included as a static JAR rather than dynamically via Gradle:

    -I /opt/android-sdk/platforms/android-22/android.jar

**Comment by norvinjohn** [comment]
Thanks you very much @dpa99c. Sorry for the late response. I did remove android 4.1 and add android 5.0.0, now the build is complete.

What could be the effect on the app if the JAR file is static?

Thanks again than @dpa99c now I can continue playing with my app :D
