### ISSUE TITLE
Android < 13 ACCESS_BACKGROUND_LOCATION is automatically granted despite it's not true

### ISSUE THREAD

**Issue by askona** [dpa99c/cordova-diagnostic-plugin#508]
I'm requesting **when_in_use** permission, and then, if it's granted, requesting **always**. 
The issue is that on Android lower then 13 **always** is not being requested, and I found why.
JS:
`this.diagnostic.requestLocationAuthorization('**when_in_use**') // first dialog - is being showed up
            .then((status) => {
                return this.diagnostic.requestLocationAuthorization('**always**'); // this dialog is NOT showing on Android < 13
            });
 `
            
            
This is why it doesn't show second - it assumes _ACCESS_BACKGROUND_LOCATION_ is already granted. But as result - user still have "**when_in_use**" permission level. If I remove that line:
`permission.equals("ACCESS_BACKGROUND_LOCATION"),` 
I'll be able to see both dialogs - request for **when_in_use** and for **always**

<img width="1034" alt="Screenshot 2023-11-09 at 10 36 59" src="https://github.com/dpa99c/cordova-diagnostic-plugin/assets/12323173/0187c4be-3ec6-4fa4-856d-9becbbb4eb9f">

**Comment by dpa99c** [comment]
I see the problem here: `ACCESS_BACKGROUND_LOCATION` was added in API 29 but this is assuming it was added in API 33.
I should be able to make use of the min/max SDK definitions I added in a [previous commit](https://github.com/dpa99c/cordova-diagnostic-plugin/commit/79817b7f1f19fbed5867b893ac05a93769126db4)  to resolve this.
