### ISSUE TITLE
Uncaught ReferenceError: module is not defined in Worklight 7.1

### ISSUE THREAD

**Issue by sunilmhetre** [dpa99c/cordova-diagnostic-plugin#53]
Hi,
    I am using the cordova plugin in my MobileFirst Platform foundation 7.1 
(eclipse plugin). I have installed the cordova-diagnostic-plugin malually.
When I try to run the project I face following error

Uncaught ReferenceError: module is not defined		diagnostic.js 669

So can you help me to understand why this issue is been occured? 

I have done following workaround to resolve the issue.

window.Diagnostic = new Diagnostic();

**Comment by dpa99c** [comment]
This is not enough information to indicate a bug or diagnose a problem. The error message would indicate the plugin's Javascript module has not been found. The cause could be due to a number of reasons, such as running on an unsupported platform or the plugin not being properly installed.

Please give the following information:

- The **entire** verbose console output of the failed build
- The **exact** process used to install the plugin
- The version of the plugin
- The versions of Cordova CLI and the Cordova platform on which the issue was observed
- OS version(s) and device (or emulator) model(s) on which the problem was observed
- Code example of calling the plugin which results in the observed issue

Please also see the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) which is a known working code base. Try building and running the example app in the same environment as you have issues with.

Without this information, it won't be possible to diagnose a problem. Please post the requested information or this issue will be closed. You have already opened a similar issue (#45) and failed to provide detailed information. Please don't open another duplicate issue or you will be banned from this repo.

**Comment by sunilmhetre** [comment]
Hey thanks for the reply. I think the issue is because of the plugin is not being installed properly in to the mobile first studio project. Now we are moving to use mobile first cordova project. Thanks again for the reply....
