### ISSUE TITLE
Uncaught TypeError: Cannot read property 'diagnostic' of undefined

### ISSUE THREAD

**Issue by yokesharun** [dpa99c/cordova-diagnostic-plugin#54]
while compiling its showing Uncaught TypeError: Cannot read property 'diagnostic' of undefined

**Comment by dpa99c** [comment]
This is not enough information to indicate a bug or diagnose a problem. However, from the error message, this would indicate the plugin's Javascript module has not been found. The cause could be due to a number of reasons, such as running on an unsupported platform or the plugin not being properly installed.

Please give the following information:

- A clear description of the problem
- The **entire** verbose console output of the failed build
- OS version(s) and device (or emulator) model(s) on which the problem was observed
- Code example of calling the plugin which results in the observed issue
- Example parameters (locations or place names) which results in the observed issue

Without this information, it won't be possible to diagnose a problem and hence the issue will be closed.
