### ISSUE TITLE
Support for both Android API 23 and 19 for isLocationEnabled?

### ISSUE THREAD

**Issue by Ionian316** [dpa99c/cordova-diagnostic-plugin#58]
Hi, I'm not clear from reading the documentation about using the latest version to call `isLocationEnabled()`. If I use the latest version and build using SDK version 23, will the function return the correct value when called from both Marshmallow (API 23) and a KitKat (API 19) devices?

**Comment by dpa99c** [comment]
Android SDKs are backwardly compatible, so if you build for API 23 it will work fine on API 19. 

When API 23 runtime permissions code is executed on a device running Android 5 or below, the permissions will just always return as GRANTED at runtime since on older Android they are allocated at install time.

So isLocationEnabled() will return the correct value on Marshmallow and Kitkat
