### ISSUE TITLE
Plugin Not Installed

### ISSUE THREAD

**Issue by kSakthiraj** [dpa99c/cordova-diagnostic-plugin#59]
Plugin is Not Installing Properly on Cordova version 6.1.1

**Comment by dpa99c** [comment]
This is not enough information to indicate a bug or diagnose a problem.

Please give the following information:

- The **exact** error message 
- The **entire** verbose console output of the failed install operation 
- The **exact** process used to install the plugin
- The version of this plugin and the Cordova platform on which the issue was observed
- OS version(s) on which the problem was observed

Please also see the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) which is a known working code base. Try building and running the example app in the same environment as you have issues with.

Without this information, it won't be possible to diagnose a problem. Please post the requested information or this issue will be closed.

**Comment by sanjivanig** [comment]
I am facing the same issue for this plugin :
Error message - plugin_not_installed (I only get this error message)
Plugin version - 4.0.12
Node version - v10.15.0
Cordova version - 8.1.2 (cordova-lib@8.1.1)
iOS version - 4.5.5

Also, I installed the plugin using below commands :
ionic cordova plugin add cordova.plugins.diagnostic
npm install --save @ionic-native/diagnostic@4

**Comment by dpa99c** [comment]
@sanjivanig 

- `ionic cordova plugin add cordova.plugins.diagnostic` installs this plugin.
- `npm install --save @ionic-native/diagnostic@4` installs the Ionic Native Typescript wrapper for this plugin.

Which command generates the above error message?

If it's the first, run `cordova plugin add cordova.plugins.diagnostic --verbose` and post the full output here.
If it's the second check if `plugins/cordova.plugins.diagnostic` or `node_modules/codove.plugins.diagnostic` exists.

**Comment by sanjivanig** [comment]
I reinstalled the plugin and it works. Thank you
