### ISSUE TITLE
only "registerLocationAuthorizationStatusChangeHandler" not work in iOS

### ISSUE THREAD

**Issue by bau720123** [dpa99c/cordova-diagnostic-plugin#6]
hi @dpa99c 
I am using PGB 5.2.0 with your plugin with version 2.1.0 + iOS 9.0.2 (13A452)
all function perfect work in addition to "registerLocationAuthorizationStatusChangeHandler"
```
cordova.plugins.diagnostic.registerLocationAuthorizationStatusChangeHandler(function(status){
    alert("Location authorization status changed to: "+status);
});
```
no any alert appear after I change the location service on to off or off to on

**Comment by dpa99c** [comment]
`registerLocationAuthorizationStatusChangeHandler()` is called in response to an authorization change state. So if you are turning on/off the device-wide Location Services setting, the callback will not be invoked. To handle this situation, you should check the location services state when your app is resumed from the background:

    function onResume(){
        cordova.plugins.diagnostic.isLocationEnabledSetting(function(enabled){
            console.log("Location Services setting is " + (enabled ? "enabled" : "disabled"));
        }, function(error){
            console.error("The following error occurred: "+error);
        });
    }
    document.addEventListener("resume", onResume, false);

If you're changing the app-specific location authorization setting in the Settings app (e.g. "Always" to "Never"), it will not be called either. This is because the callback function registered with `registerLocationAuthorizationStatusChangeHandler()` will only be called when your app is in the foreground. If you are leaving your app to go to Settings in order to change the app-specific location authorization setting, then your app is in the background so `registerLocationAuthorizationStatusChangeHandler()` callback will not be invoked. To handle this situation, you should check the location authorization state when your app is resumed from the background:

    function onResume(){
        cordova.plugins.diagnostic.isLocationAuthorized(function(enabled){
            console.log("Location authorization is " + (enabled ? "enabled" : "disabled"));
        }, function(error){
            console.error("The following error occurred: "+error);
        });
    }
    document.addEventListener("resume", onResume, false);
    
    
In practice, `registerLocationAuthorizationStatusChangeHandler()` is only useful when the location authorization is requested for the first time and the native dialog pops up asking the user to allow or deny location access by the app. This only happens the first time the app is run and when location authorization status changes from "not_determined" to "authorized_always" or "authorized_when_in_use". When the user presses either "OK" or "Don't Allow" in the native dialog, the registered callback will be invoked. For example:

    function onChangeLocationAuthorizationStatus(newStatus){
        console.log("New location authorization status: " + newStatus);
    }

    function onDeviceReady(){
        cordova.plugins.diagnostic.registerLocationAuthorizationStatusChangeHandler(onChangeLocationAuthorizationStatus);
        
        cordova.plugins.diagnostic.getLocationAuthorizationStatus(function(status){
            console.log("Location authorization status: " + status);
            if(status == "not_determined"){
                cordova.plugins.diagnostic.requestLocationAuthorization(function(){ // This will trigger a call to onChangeLocationAuthorizationStatus()
                    console.log("Requested location authorisation");
                }, onError, "always");
            }
        },  onError);
    }
    document.addEventListener("deviceready", onDeviceReady, false);

**Comment by dpa99c** [comment]
Can this be closed?

**Comment by bau720123** [comment]
OKOK
I just see your post
close first!!!
thanks @dpa99c
