### ISSUE TITLE
The plugin is breaking the code

### ISSUE THREAD

**Issue by dhavalkakkad** [dpa99c/cordova-diagnostic-plugin#63]
Hi there,

I have android SDK 23 installed, I want to use the features you guys are offering, but every time I add the code it give me the error,  " Uncaught TypeError:Cannot read Property 'diagnostic' of undefined ".

This is the code I am using. 

function onDeviceReady(){
cordova.plugins.diagnostic.isLocationEnabled(function(enabled){
    alert("Location is " + (enabled ? "enabled" : "disabled"));
}, function(error){
    alert("The following error occurred: "+error);
});

}

Don't know what should I do ?.. I am using phonegap and most of the code is in angular JS.

Any help is appreciated. Thanks in advance.

**Comment by dpa99c** [comment]
The error message would indicate the plugin's Javascript module has not been found. The cause could be due to a number of reasons, such as running on an unsupported platform or the plugin not being properly installed.

The following information would be useful is diagnosing the problem:

- The **exact** process used to install the plugin
- The version of the plugin
- The versions of Cordova CLI and the Cordova platform on which the issue was observed
- OS version(s) and device (or emulator) model(s) on which the problem was observed

Please also try building and running the example app in the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) in the same environment as you have issues with. This is a known working code base, so should help eliminate other possible causes, such as another plugin interfering with this one.

**Comment by dpa99c** [comment]
Reopen if still an issue
