### ISSUE TITLE
cordova can oly give me old version +  isLocationEnabled() is not working

### ISSUE THREAD

**Issue by grapemix** [dpa99c/cordova-diagnostic-plugin#7]
First, thanks for your work. I was looking for this plugin.Unfortunately, I ran into two problems. 

I install the plugin follow the instruction in my local:

$ cordova plugin add cordova.plugins.diagnostic
Fetching plugin "cordova.plugins.diagnostic" via cordova plugins registry
npm http GET http://registry.cordova.io/cordova.plugins.diagnostic
npm http 200 http://registry.cordova.io/cordova.plugins.diagnostic
npm http GET http://cordova.iriscouch.com/registry/_design/app/_rewrite/cordova.plugins.diagnostic/-/cordova.plugins.diagnostic-1.1.0.tgz
npm http 200 http://cordova.iriscouch.com/registry/_design/app/_rewrite/cordova.plugins.diagnostic/-/cordova.plugins.diagnostic-1.1.0.tgz
Installing "cordova.plugins.diagnostic" for android
Installing "cordova.plugins.diagnostic" for ios

The version is 1.1.0, but not 2.1.0 listed in npm?! Some how the cordova use the version in Cordova Registry. Any idea? BTW, I also used phonegap build too(<gap:plugin name="cordova.plugins.diagnostic" source="npm" />), but I cannot validate the version thru their UI.

2 problem:
When my gps settings is totally off(GPS+wifi), the following code will still return me success, having an alert claiming the device is gps ready:

  function checkLocationState(){
    cordova.plugins.diagnostic.isLocationEnabled(
      function(){alert("ready?");},
      function(err){
        var settingFxn;
        if($rootScope.UTIL.osType = "android")
          settingFxn = cordova.plugins.diagnostic.switchToLocationSettings;
        else
          settingFxn = cordova.plugins.diagnostic.switchToSettings;
        settingFxn(
          function(){
            alert("Successfully switched to Settings app");
          }, 
          function(error){
            alert("The following error occurred: "+error);
        });
      });
  }
  document.addEventListener('resume', checkLocationState, false);
  document.addEventListener('deviceready', checkLocationState, false);

The problem is in iOS and Android.

Just FYI, we use local build to test Android and phonegap build to test iOS.

**Comment by dpa99c** [comment]
I can say with almost certaintly that your problem is you have an outdated version of the Cordova CLI. You can confirm this by simply typing `cordova -v`. If the version is any less than 5.0.0, there's your problem. To update to the most recent version, use `npm install -g cordova`.

Since version 5.0.0, cordova has switched to use [npmjs](https://www.npmjs.com/) as its plugin registry, but earlier versions (3.x-4.x) still use the now deprecated [Cordova Plugin Repository](http://plugins.cordova.io/) as the primary plugin registry. The Cordova Plugin Repository is now immutablable (read-only) which means that any plugins on there are likely to be out-of-date, including this one. The last version of `cordova.plugins.diagnostic` published [here](http://plugins.cordova.io/#/package/cordova.plugins.diagnostic) was v1.1.0. Whereas the [version on npmjs](https://www.npmjs.com/package/cordova.plugins.diagnostic) is now v2.1.0.

Note that in v2.1.0, `cordova.plugins.diagnostic.isLocationEnabled()` returns true on Android if GPS **or** network location (Wifi/cell triangulation) is enabled. To specifically test if GPS is enabled, use `cordova.plugins.diagnostic.isGpsLocationEnabled()`

On iOS, it is not possible to differentiate between GPS and network location providers, so `cordova.plugins.diagnostic.isLocationEnabled()` returns true if Location Services is enabled **and** the app has been authorized to use location.

**Comment by grapemix** [comment]
Thanks for your reply. I really wish your guess it true, then I can resolve this problem quick. 

The android version of my app works perfectly now, but the iOS version of app still have problem.

Let's assume my local env is broken, the phonegap build should be fine, right? As I mentioned earlier,  my iOS app is built in phonegap clould platform, so I assume the version should not be the problem as I used <gap:plugin name="cordova.plugins.diagnostic" source="npm" /> in my config.xml(I cannot confirm the version since the build log does not show me the version) 

Right now, the cordova.plugins.diagnostic.isLocationEnabled is fine in iOS, but the cordova.plugins.diagnostic object does not have switchToSettings function 0.O

Do you still suspect the plugin version is the problem or do you have a second thought?

Thanks.

**Comment by dpa99c** [comment]
If `cordova.plugins.diagnostic.switchToSettings()` is not defined, then it's almost certain you're including an old version of the plugin. I've no experience with Phonegap Build (I build everything locally), but you should make sure you're specifying npm as the plugin repository:

    <gap:plugin name="cordova.plugins.diagnostic" source="npm" />

and *not* Cordova Plugin Repository:

    <gap:plugin name="cordova.plugins.diagnostic" source="plugins.cordova.io" />

**Comment by dpa99c** [comment]
Can this be closed?
