### ISSUE TITLE
Nice Plugin.. But issue in Android 6

### ISSUE THREAD

**Issue by ashvin777** [dpa99c/cordova-diagnostic-plugin#72]
This plugin some time for Android 6 .. using isLocationEnabled() gives false even if the location is on and on high accuracy. Can you check

**Comment by dpa99c** [comment]
On Android 6, `isLocationEnabled()` will return false if location mode is ON but location access is unauthorised (`isLocationAuthorized() == FALSE`). Could this be the cause of your issues?

**Comment by ashvin777** [comment]
but in that case I have checked that the location authorization was true

**Comment by ashvin777** [comment]
Something is really wrong.. For Android 5 I have fired below commands and it not returning back anything ... 


`cordova.plugins.diagnostic.isLocationAuthorized(function(enabled) { console.log(enabled);}, function(e){ console.log(e);});
undefined
cordova.plugins.diagnostic.isLocationEnabled(function(enabled) { console.log(enabled);}, function(e){ console.log(e);});
undefined
cordova.plugins.diagnostic.isGpsLocationEnabled(function(enabled) { console.log(enabled);}, function(e){ console.log(e);});
undefined
`

Above are the logs from console. I am hitting directly these commands in console. Sometime it works but sometime it doesnt response. Not even it goes to error. My wifi and location both are swtiched on.

**Comment by dpa99c** [comment]
This is strange, as I'm not observing any intermittent behaviour when I testing the plugin via the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) on Android 5 and 6. 

As you can see from the [Android source code](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/src/android/Diagnostic.java), this plugin is just a thin wrapper around the native APIs offered by Android, and therefore there's very little in the plugin code that could explain such intermittent behaviour.

OK, let's try to eliminate some variables here: firstly, if you build and run the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example), do you observe the same behaviour? This should eliminate the possibility of the issue being caused by a factor in your project such as another plugin.

If you still observe the same issues when building the example project, then try downloading and installing [this APK](http://ge.tt/1LuyCwa2) which contains the example project built in my local dev environment:

- Plugin version: `cordova.plugins.diagnostic@3.0.1`
- Cordova CLI: v6.1.1
- Cordova Android platform: v5.1.1

This should eliminate any possible differences in our build environments.

**Comment by dpa99c** [comment]
Reopen if still an issue
