### ISSUE TITLE
Not working in Windows Phone 8.1

### ISSUE THREAD

**Issue by ashvin777** [dpa99c/cordova-diagnostic-plugin#73]
I am not able to use this plugin in windows phone. Getting below error

`Exception calling native with command :: Diagnostic :: isLocationEnabled ::exception=TypeError: Object doesn't support property or method 'requestAccessAsync'`

Regards,
Ashvin

**Comment by dpa99c** [comment]
Currently, the plugin only supports Windows 10 and Windows 10 Mobile, not Windows Phone 8.1.

The reason being that the native functionality required by the plugin's current Windows implementation is only available since Windows 10. 

For example, in the error case you have given above, `isLocationEnabled()` [invokes](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/src/windows/diagnosticProxy.js#L19) `Windows.Devices.Geolocation.Geolocator.requestAccessAsync()`. And as the [Microsoft documentation states](https://msdn.microsoft.com/library/windows/apps/windows.devices.geolocation.geolocator.requestaccessasync.aspx), this was only introduced in Windows 10.

Windows Phone 8.1 would require a different implementation (even if possible), and at this time I don't plan to add that, since the Windows 8.1 global marketshare is below 5% and falling, and is also rendered obsolete by Windows 10 Mobile.

However, the plugin documentation should probably explicitly state all of this and also explicitly target Window 10 Mobile platform in the config.xml. I will update the plugin to do both of these.
