### ISSUE TITLE
Facing issue with getPermissionAuthorizationStatus() and requestRuntimePermission()

### ISSUE THREAD

**Issue by mohitagarwal124** [dpa99c/cordova-diagnostic-plugin#77]
Plugin is good but i am facing issue when i am using getPermissionAuthorizationStatus() and requestRuntimePermission() in order to get runtime permission for gallery(READ_EXTERNAL_STORAGE). The issue is even though if the permission is granted, it asks for permission again and again. Currently i used getCameraAuthorizationStatus() and requestCameraAuthorization() in order to solve it. But it is not fair to ask user for camera access when they are trying to access gallery. 
I have added permission for both Camera and Storage in Android Manifest.
My Target API is 23.
Running on Moto G 2nd gen -- Android M.
Please solve it, looking forward to  your response.

**Comment by dpa99c** [comment]
It depends how you are requesting access to the gallery as to what the cause of your issue is. For example, if you are using [cordova-plugin camera](https://github.com/apache/cordova-plugin-camera), there's a [documented bug](https://github.com/apache/cordova-plugin-camera/blob/master/src/android/CameraLauncher.java#L176) that causes it to continually re-request permission.

For the purposes of validating the behaviour of this plugin, you should try to build/run the [runtime permissions example project](https://github.com/dpa99c/cordova-diagnostic-plugin-android-runtime-example) which allows all Android runtime permissions to be requested and demonstrates that, once requested, no permissions are able to be re-requested once granted.

**Comment by dpa99c** [comment]
Reopen if still an issue
