### ISSUE TITLE
after plugin install not run project

### ISSUE THREAD

**Issue by ominfowave** [dpa99c/cordova-diagnostic-plugin#82]
![capture](https://cloud.githubusercontent.com/assets/4697885/15930566/4110ee38-2e71-11e6-9635-4a0805acc39b.PNG)

**Comment by ominfowave** [comment]
please help

**Comment by dpa99c** [comment]
This build error is caused either because the Android target SDK is not set to API 23 or because the necessary library dependencies are not installed:

In order to support Android 6 (API 23) [runtime permissions](http://developer.android.com/training/permissions/requesting.html), this plugin must depend on libraries only present in API 23+, so you __must build using Android SDK Platform v23 or above__. To do this you must have [Cordova Android platform](https://github.com/apache/cordova-android)@5.0.0 or above installed in your project. You can check the currently installed platform versions with the following command:

    cordova platform ls

You __must__ also make sure your build environment has the following Android libraries installed. In a local build environment, you'd install these via the Android SDK Manager:

 -  Android Support Library - Rev. 23 or above
 -  Android Support Repository - Rev. 23 or above

**Comment by dpa99c** [comment]
Reopen if still an issue
