### ISSUE TITLE
Camera permissions not working correctly on Android

### ISSUE THREAD

**Issue by dbuschtoens** [dpa99c/cordova-diagnostic-plugin#88]
When the camera access is not yet requested, `getCameraAuthorizationStatus()` correctly returns the `NOT_REQUESTED` status. When it is denied, the status is correclty `DENIED`. However, both when access has been granted and when it has been denied with the "don't ask again" checkbox checked, the status incorrectly returns as `NOT_REQUESTED`.
The `getPermissionAuthorizationStatus()` with argument `cordova.plugins.diagnostic.runtimePermission.CAMERA` behaves the same, `isCameraAuthorized()` also returns `false` when access is granted.
This was tested on two devices:

- Nexus 5 Android Version 6.0.1
- Galaxy S6 Android Version 6.0.1

**Comment by dpa99c** [comment]
The native Android 6 runtime permissions API does not enable distinguishing between NOT_REQUESTED and DENIED_ALWAYS. To work around this, this plugin [uses local storage](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/www/android/diagnostic.js#L136) to set a flag upon first requesting a given permission, therefore enabling it to distinguish between these two states.

If you are seeing `NOT_REQUESTED` being returned when you expecting `DENIED_ALWAYS`, it is likely due to an issue with local storage: 

- if you are using Crosswalk, this has known issues with persisting state in local storage
- make sure your application code is not blanket clearing all of local storage (i.e. `localStorage.clear()`)

I would also advise building and testing the [runtime permissions example project](https://github.com/dpa99c/cordova-diagnostic-plugin-android-runtime-example) while illustrates use of this plugin for managing runtime permissions. Build and test this in the same environment you are encountering this issue with to determine if it's reproducible with the example project. 

Otherwise, I'd recommend use Chrome Dev Tools to remotely inspect the Cordova WebView when the app is running on the devices in order to monitor the values being stored in local storage.

**Comment by dpa99c** [comment]
Reopen if still an issue
