### ISSUE TITLE
IOS 9 : isLocationEnabled always returns location disabled (V >= 2.1)

### ISSUE THREAD

**Issue by mellinas** [dpa99c/cordova-diagnostic-plugin#9]
Hi,

Since the version 2.1.0 of this plugin and IOS improvements, I can't use IsLocationEnabled on my Iphone 4s (IOS v9.0.2).

If I use version 2.0.1, all is working fine

**Comment by dpa99c** [comment]
In v2.0.1 and below, `isLocationEnabled()` returned true if Location Services is on and if authorization status was not [denied](https://developer.apple.com/library/mac/documentation/CoreLocation/Reference/CLLocationManager_Class/#//apple_ref/c/econst/kCLAuthorizationStatusDenied).

However, this was incorrect because `isLocationEnabled()` is supposed to return true only if location is available to the app. If authorization status was [not determined](https://developer.apple.com/library/mac/documentation/CoreLocation/Reference/CLLocationManager_Class/#//apple_ref/c/econst/kCLAuthorizationStatusNotDetermined), `isLocationEnabled()` was returning true, but the app hadn't yet requested location authorization, so location info is not available to the app.

So v2.1.0 changed `isLocationEnabled()` to only return true if location access has been authorized, either [always](https://developer.apple.com/library/watchos/documentation/CoreLocation/Reference/CLLocationManager_Class/index.html#//apple_ref/c/econst/kCLAuthorizationStatusAuthorizedAlways) or [when in use](https://developer.apple.com/library/watchos/documentation/CoreLocation/Reference/CLLocationManager_Class/index.html#//apple_ref/c/econst/kCLAuthorizationStatusAuthorizedWhenInUse).

So if you're using v2.1.0 or higher and `isLocationEnabled()` is returning false, it's because either Location Services is off, authorization has been denied OR authorization hasn't been requested yet.

You can use [requestLocationAuthorization()](https://github.com/dpa99c/cordova-diagnostic-plugin#requestlocationauthorization) to ask the user to authorize location use by the app.

**Comment by mellinas** [comment]
Ah ok, the process has changed,

In fact in my case, I need the requestLocationAuthorization,

Thank you for the explanation
