### ISSUE TITLE
locationAuthorizationMode is not exposed

### ISSUE THREAD

**Issue by nicoabie** [dpa99c/cordova-diagnostic-plugin#90]
cordova.plugins.diagnostic.locationAuthorizationMode is undefined

**Comment by dpa99c** [comment]
locationAuthorizationMode is [exposed here](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/www/ios/diagnostic.js#L37) by the iOS plugin API and can be seen [in use here](https://github.com/dpa99c/cordova-diagnostic-plugin-example/blob/master/www/js/index.js#L85) in the example app - you can confirm this is working by building and running the example project .

If you're still have issues with your own code, please post more useful information such as the platform version, cordova cli version, plugin version and code snippet illustrating usage.

**Comment by nicoabie** [comment]
Sorry for the lack of info. 
The problem is on android, the method requestLocationAuthorization is supposed to work on android and ios, but just on ios locationAuthorizationMode is defined.
Therefore using it on android causes errors, the documentation gives an example for each platform and it was my bad undestanding that thought there ain't no problem using the same code for both.
That is not the case but it think it should be.

**Comment by dpa99c** [comment]
OK, I think I understand your issue. Since on Android `locationAuthorizationMode` makes no sense (since there's not concept of ALWAYS or WHEN_IN_USE like on iOS), then there wouldn't be any sensible values to define within it, but if it were defined as an empty object, then any references to keys inside it would evaluate to undefined but at least this wouldn't raise an error.

So for the next version I will add for the Android version: 

    cordova.plugins.diagnostic.locationAuthorizationMode = {};

This will allow you to use the same code on both Android and iOS:

    cordova.plugins.diagnostic.requestLocationAuthorization(
        onSuccess, 
        onError, 
        cordova.plugins.diagnostic.locationAuthorizationMode.ALWAYS
    );

**Comment by nicoabie** [comment]
Exactly Dave. I understand it makes no sense in android, it is just to make it easier to use. 
Thanks.
