### ISSUE TITLE
[ANDROID] getBluetoothState returns a Cached value. 

### ISSUE THREAD

**Issue by WebDevBren** [dpa99c/cordova-diagnostic-plugin#97]
We've been having some issues with getBluetoothState , and it returning powered_on when it is off. and vise-versa. 

we managed to get this to work as intended by adding the BluetoothStateChangeHandler. and now it properly updates.

(all the Handler does is log the current state. its sufficient for now.)  

Is this Intended behaviour?

Also issue hasn't been noted on IOS, but could very well be present.

**Comment by dpa99c** [comment]
I will push out a fix to ensure Android always returns the current state when calling `getBluetoothState()`. 

The iOS implementation will always correctly return the current state via `getBluetoothState()` because `centralManagerDidUpdateState` is invoked at app startup to notify of the current state and then on any subsequent change to the Bluetooth state.
